// <auto-generated />
using System;
using Bingo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bingo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260711172420_AddEventsAndSignups")]
    partial class AddEventsAndSignups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bingo.Domain.Access.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("active_from");

                    b.Property<DateTimeOffset?>("CorrectionOnlyFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("correction_only_from");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_username");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Auditing.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_account_id");

                    b.Property<string>("ActorUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("actor_username");

                    b.Property<string>("Details")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("details");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("TargetId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_type");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("Action", "TargetType");

                    b.ToTable("audit_entries", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Events.BingoEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowPrivateSignupEditing")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_private_signup_editing");

                    b.Property<bool>("BoardPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("board_published");

                    b.Property<string>("BuyInDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("buy_in_description");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<bool>("DraftLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("draft_locked");

                    b.Property<bool>("DraftResultsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("draft_results_published");

                    b.Property<DateTimeOffset>("EventEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_ends_at");

                    b.Property<DateTimeOffset>("EventStartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_starts_at");

                    b.Property<int?>("ExpectedBoardColumns")
                        .HasColumnType("integer")
                        .HasColumnName("expected_board_columns");

                    b.Property<int?>("ExpectedBoardRows")
                        .HasColumnType("integer")
                        .HasColumnName("expected_board_rows");

                    b.Property<int?>("ExpectedTeamCount")
                        .HasColumnType("integer")
                        .HasColumnName("expected_team_count");

                    b.Property<int?>("ExpectedTeamSize")
                        .HasColumnType("integer")
                        .HasColumnName("expected_team_size");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("ParticipantCap")
                        .HasColumnType("integer")
                        .HasColumnName("participant_cap");

                    b.Property<bool>("ParticipantListPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("participant_list_published");

                    b.Property<string>("PrizeDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("prize_description");

                    b.Property<string>("PublicRules")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("public_rules");

                    b.Property<bool>("RequireSignupCode")
                        .HasColumnType("boolean")
                        .HasColumnName("require_signup_code");

                    b.Property<bool>("ResultsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("results_published");

                    b.Property<DateTimeOffset>("SignupClosesAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signup_closes_at");

                    b.Property<string>("SignupCodeHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("signup_code_hash");

                    b.Property<DateTimeOffset>("SignupOpensAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signup_opens_at");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("SubmissionCutoffAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submission_cutoff_at");

                    b.Property<bool>("TeamRostersPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("team_rosters_published");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("timezone");

                    b.Property<bool>("WaitingListEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("waiting_list_enabled");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Events.EventStateTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("from_state");

                    b.Property<DateTimeOffset>("PerformedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at");

                    b.Property<Guid>("PerformedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("performed_by_account_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("to_state");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "PerformedAt");

                    b.ToTable("event_state_transitions", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Signups.EventParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("admin_notes");

                    b.Property<bool>("CaptainVolunteer")
                        .HasColumnType("boolean")
                        .HasColumnName("captain_volunteer");

                    b.Property<string>("Comments")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("comments");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<string>("DiscordIdentity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("discord_identity");

                    b.Property<decimal>("EhbSnapshot")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("ehb_snapshot");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("FormVersion")
                        .HasColumnType("integer")
                        .HasColumnName("form_version");

                    b.Property<string>("NormalizedPrimaryAccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_primary_account_name");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("payment_status");

                    b.Property<string>("PrimaryAccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("primary_account_name");

                    b.Property<string>("PrivateEditTokenHash")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("private_edit_token_hash");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<string>("SecondAccountName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("second_account_name");

                    b.Property<DateTimeOffset>("SignedUpAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signed_up_at");

                    b.Property<long>("SignupSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("signup_sequence");

                    b.Property<string>("SignupStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("signup_status");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("status_reason");

                    b.Property<DateTimeOffset?>("WaitingListedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("waiting_listed_at");

                    b.Property<DateTimeOffset?>("WithdrawnAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("withdrawn_at");

                    b.HasKey("Id");

                    b.HasIndex("PrivateEditTokenHash")
                        .IsUnique();

                    b.HasIndex("EventId", "NormalizedPrimaryAccountName");

                    b.HasIndex("EventId", "SignupSequence")
                        .IsUnique();

                    b.ToTable("event_participants", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Signups.SignupAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EventParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_participant_id");

                    b.Property<string>("QuestionLabelSnapshot")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("question_label_snapshot");

                    b.Property<Guid>("SignupQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("signup_question_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("EventParticipantId", "SignupQuestionId")
                        .IsUnique();

                    b.ToTable("signup_answers", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Signups.SignupQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("HelpText")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("help_text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("label");

                    b.Property<string>("Options")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("options");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean")
                        .HasColumnName("required");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "Key")
                        .IsUnique();

                    b.ToTable("signup_questions", (string)null);
                });

            modelBuilder.Entity("Bingo.Infrastructure.Persistence.SystemMetadata", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("system_metadata", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
