// <auto-generated />
using System;
using Bingo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bingo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260721232916_AddBoardEditorAndCatalogueRateMechanics")]
    partial class AddBoardEditorAndCatalogueRateMechanics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bingo.Domain.Access.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("active_from");

                    b.Property<Guid?>("CaptainParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("captain_participant_id");

                    b.Property<DateTimeOffset?>("CorrectionOnlyFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("correction_only_from");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_username");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("CaptainParticipantId")
                        .IsUnique();

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Auditing.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_account_id");

                    b.Property<string>("ActorUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("actor_username");

                    b.Property<string>("Details")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("details");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("TargetId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_type");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("Action", "TargetType");

                    b.ToTable("audit_entries", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Boards.Board", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CalculationVersion")
                        .HasColumnType("integer")
                        .HasColumnName("calculation_version");

                    b.Property<int>("Columns")
                        .HasColumnType("integer")
                        .HasColumnName("columns");

                    b.Property<long>("EditControlVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("edit_control_version");

                    b.Property<Guid?>("EditorAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("editor_account_id");

                    b.Property<DateTimeOffset?>("EditorLeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("editor_lease_expires_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("Rows")
                        .HasColumnType("integer")
                        .HasColumnName("rows");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("state");

                    b.Property<decimal>("TotalEhbEstimate")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("total_ehb_estimate");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("boards", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Boards.BoardRequirementBossSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BossActivityId")
                        .HasColumnType("uuid")
                        .HasColumnName("boss_activity_id");

                    b.Property<string>("BossName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("boss_name");

                    b.Property<decimal?>("EfficientRate")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("efficient_rate");

                    b.Property<Guid>("RequirementId")
                        .HasColumnType("uuid")
                        .HasColumnName("requirement_id");

                    b.HasKey("Id");

                    b.ToTable("board_requirement_boss_snapshots", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Boards.BoardRequirementDropSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BossName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("boss_name");

                    b.Property<int>("CreditedWeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("credited_weight");

                    b.Property<string>("DisplayRate")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_rate");

                    b.Property<decimal?>("EhbPerContribution")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("ehb_per_contribution");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("item_name");

                    b.Property<int?>("MaximumContribution")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_contribution");

                    b.Property<decimal?>("NumericProbability")
                        .HasPrecision(18, 12)
                        .HasColumnType("numeric(18,12)")
                        .HasColumnName("numeric_probability");

                    b.Property<Guid>("RequirementId")
                        .HasColumnType("uuid")
                        .HasColumnName("requirement_id");

                    b.Property<Guid>("SourceDropId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_drop_id");

                    b.HasKey("Id");

                    b.ToTable("board_requirement_drop_snapshots", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Boards.BoardRequirementSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowHigherWeightings")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_higher_weightings");

                    b.Property<Guid>("BoardTileId")
                        .HasColumnType("uuid")
                        .HasColumnName("board_tile_id");

                    b.Property<int>("CreditedWeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("credited_weight");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("DuplicatesAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("duplicates_allowed");

                    b.Property<bool>("ManualObjective")
                        .HasColumnType("boolean")
                        .HasColumnName("manual_objective");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<int>("TargetContribution")
                        .HasColumnType("integer")
                        .HasColumnName("target_contribution");

                    b.HasKey("Id");

                    b.ToTable("board_requirement_snapshots", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Boards.BoardTile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid")
                        .HasColumnName("board_id");

                    b.Property<int>("ColumnIndex")
                        .HasColumnType("integer")
                        .HasColumnName("column_index");

                    b.Property<string>("DescriptionSnapshot")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description_snapshot");

                    b.Property<decimal>("EstimatedEhbSnapshot")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("estimated_ehb_snapshot");

                    b.Property<string>("EvidenceInstructionsSnapshot")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("evidence_instructions_snapshot");

                    b.Property<string>("ImageUrlSnapshot")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("image_url_snapshot");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_snapshot");

                    b.Property<int>("RowIndex")
                        .HasColumnType("integer")
                        .HasColumnName("row_index");

                    b.Property<Guid>("TileTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("tile_template_id");

                    b.HasKey("Id");

                    b.HasIndex("BoardId", "RowIndex", "ColumnIndex")
                        .IsUnique();

                    b.ToTable("board_tiles", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Boards.TemplateRequirementBoss", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BossActivityId")
                        .HasColumnType("uuid")
                        .HasColumnName("boss_activity_id");

                    b.Property<Guid>("RequirementId")
                        .HasColumnType("uuid")
                        .HasColumnName("requirement_id");

                    b.HasKey("Id");

                    b.HasIndex("RequirementId", "BossActivityId")
                        .IsUnique();

                    b.ToTable("template_requirement_bosses", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Boards.TemplateRequirementDrop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CreditedWeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("credited_weight");

                    b.Property<int?>("MaximumContribution")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_contribution");

                    b.Property<Guid>("RequirementId")
                        .HasColumnType("uuid")
                        .HasColumnName("requirement_id");

                    b.Property<Guid>("SourceDropId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_drop_id");

                    b.HasKey("Id");

                    b.HasIndex("RequirementId", "SourceDropId")
                        .IsUnique();

                    b.ToTable("template_requirement_drops", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Boards.TileTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("EvidenceInstructions")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("evidence_instructions");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("image_url");

                    b.Property<decimal?>("ManualEhbOverride")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("manual_ehb_override");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ObjectiveType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("objective_type");

                    b.HasKey("Id");

                    b.ToTable("tile_templates", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Boards.TileTemplateRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowHigherWeightings")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_higher_weightings");

                    b.Property<int>("CreditedWeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("credited_weight");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("DuplicatesAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("duplicates_allowed");

                    b.Property<bool>("ManualObjective")
                        .HasColumnType("boolean")
                        .HasColumnName("manual_objective");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<int>("TargetContribution")
                        .HasColumnType("integer")
                        .HasColumnName("target_contribution");

                    b.Property<Guid>("TileTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("tile_template_id");

                    b.HasKey("Id");

                    b.HasIndex("TileTemplateId", "Position")
                        .IsUnique();

                    b.ToTable("tile_template_requirements", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Catalogue.BossActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("DataSource")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("data_source");

                    b.Property<DateTimeOffset>("DataUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_updated_at");

                    b.Property<decimal?>("EfficientCompletionsPerHour")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("efficient_completions_per_hour");

                    b.Property<string>("ExternalIdentifier")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_identifier");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("boss_activities", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Catalogue.CatalogueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("ExternalIdentifier")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_identifier");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_name");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("catalogue_items", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Catalogue.SourceDrop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<int>("AssumedParticipants")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("assumed_participants");

                    b.Property<Guid>("BossActivityId")
                        .HasColumnType("uuid")
                        .HasColumnName("boss_activity_id");

                    b.Property<bool>("ConditionalOnParent")
                        .HasColumnType("boolean")
                        .HasColumnName("conditional_on_parent");

                    b.Property<string>("DataSource")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("data_source");

                    b.Property<DateTimeOffset>("DataUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_updated_at");

                    b.Property<decimal?>("DefaultEhbEstimate")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("default_ehb_estimate");

                    b.Property<string>("DisplayRate")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_rate");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<decimal?>("NumericProbability")
                        .HasPrecision(18, 12)
                        .HasColumnType("numeric(18,12)")
                        .HasColumnName("numeric_probability");

                    b.Property<decimal?>("ParentProbability")
                        .HasPrecision(18, 12)
                        .HasColumnType("numeric(18,12)")
                        .HasColumnName("parent_probability");

                    b.Property<string>("ProbabilityScope")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Participant")
                        .HasColumnName("probability_scope");

                    b.Property<string>("RateConditionNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("rate_condition_note");

                    b.Property<string>("RollGroup")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasDefaultValue("default")
                        .HasColumnName("roll_group");

                    b.Property<int>("RollsPerCompletion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("rolls_per_completion");

                    b.HasKey("Id");

                    b.HasIndex("BossActivityId", "ItemId")
                        .IsUnique();

                    b.ToTable("source_drops", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Catalogue.SourceDropRateVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Condition")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("condition");

                    b.Property<string>("DisplayRate")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("display_rate");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("label");

                    b.Property<decimal?>("NumericProbability")
                        .HasPrecision(18, 12)
                        .HasColumnType("numeric(18,12)")
                        .HasColumnName("numeric_probability");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("SourceDropId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_drop_id");

                    b.HasKey("Id");

                    b.HasIndex("SourceDropId", "Position")
                        .IsUnique();

                    b.ToTable("source_drop_rate_variants", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Events.BingoEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowPrivateSignupEditing")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_private_signup_editing");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<bool>("BoardPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("board_published");

                    b.Property<string>("BuyInDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("buy_in_description");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<bool>("DraftLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("draft_locked");

                    b.Property<bool>("DraftResultsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("draft_results_published");

                    b.Property<DateTimeOffset>("EventEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_ends_at");

                    b.Property<DateTimeOffset>("EventStartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_starts_at");

                    b.Property<bool>("EvidenceCodeEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("evidence_code_enabled");

                    b.Property<int?>("ExpectedBoardColumns")
                        .HasColumnType("integer")
                        .HasColumnName("expected_board_columns");

                    b.Property<int?>("ExpectedBoardRows")
                        .HasColumnType("integer")
                        .HasColumnName("expected_board_rows");

                    b.Property<int?>("ExpectedTeamCount")
                        .HasColumnType("integer")
                        .HasColumnName("expected_team_count");

                    b.Property<int?>("ExpectedTeamSize")
                        .HasColumnType("integer")
                        .HasColumnName("expected_team_size");

                    b.Property<DateTimeOffset?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalized_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("ParticipantCap")
                        .HasColumnType("integer")
                        .HasColumnName("participant_cap");

                    b.Property<bool>("ParticipantListPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("participant_list_published");

                    b.Property<string>("PrizeDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("prize_description");

                    b.Property<string>("PublicRules")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("public_rules");

                    b.Property<DateTimeOffset?>("ReopenedSubmissionCutoffAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reopened_submission_cutoff_at");

                    b.Property<bool>("RequireSignupCode")
                        .HasColumnType("boolean")
                        .HasColumnName("require_signup_code");

                    b.Property<bool>("ResultsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("results_published");

                    b.Property<DateTimeOffset>("SignupClosesAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signup_closes_at");

                    b.Property<string>("SignupCodeHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("signup_code_hash");

                    b.Property<DateTimeOffset>("SignupOpensAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signup_opens_at");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("SubmissionCutoffAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submission_cutoff_at");

                    b.Property<bool>("TeamRostersPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("team_rosters_published");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("timezone");

                    b.Property<bool>("WaitingListEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("waiting_list_enabled");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Events.EventFinalizationSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("FinalizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalized_at");

                    b.Property<Guid>("FinalizedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("finalized_by_account_id");

                    b.Property<string>("UnfinalizeReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("unfinalize_reason");

                    b.Property<DateTimeOffset?>("UnfinalizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unfinalized_at");

                    b.Property<Guid?>("UnfinalizedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("unfinalized_by_account_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "Version")
                        .IsUnique();

                    b.ToTable("event_finalizations", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Events.EventStateTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("from_state");

                    b.Property<DateTimeOffset>("PerformedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at");

                    b.Property<Guid>("PerformedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("performed_by_account_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("to_state");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "PerformedAt");

                    b.ToTable("event_state_transitions", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Events.FinalReviewResolution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlockerDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("blocker_description");

                    b.Property<string>("BlockerKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("blocker_key");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid>("ResolvedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_account_id");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "BlockerKey");

                    b.ToTable("final_review_resolutions", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Events.OfficialPlacementSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("BoardComplete")
                        .HasColumnType("boolean")
                        .HasColumnName("board_complete");

                    b.Property<DateTimeOffset?>("BoardCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("board_completed_at");

                    b.Property<int>("CompletedLines")
                        .HasColumnType("integer")
                        .HasColumnName("completed_lines");

                    b.Property<int>("CompletedTiles")
                        .HasColumnType("integer")
                        .HasColumnName("completed_tiles");

                    b.Property<decimal>("EhbTiebreak")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("ehb_tiebreak");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("FinalizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("finalization_id");

                    b.Property<int>("Placement")
                        .HasColumnType("integer")
                        .HasColumnName("placement");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("team_name");

                    b.HasKey("Id");

                    b.HasIndex("FinalizationId", "TeamId")
                        .IsUnique();

                    b.ToTable("official_placements", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Events.TeamCompletionCorrection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CorrectedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("corrected_by_account_id");

                    b.Property<DateTimeOffset>("CorrectedCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("corrected_completed_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "TeamId")
                        .IsUnique();

                    b.ToTable("team_completion_corrections", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Evidence.EvidenceAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_size");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("checksum");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("media_type");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_filename");

                    b.Property<int>("PixelHeight")
                        .HasColumnType("integer")
                        .HasColumnName("pixel_height");

                    b.Property<int>("PixelWidth")
                        .HasColumnType("integer")
                        .HasColumnName("pixel_width");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("role");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_account_id");

                    b.HasKey("Id");

                    b.HasIndex("Checksum");

                    b.HasIndex("SubmissionId", "Active");

                    b.ToTable("evidence_assets", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Evidence.EvidenceCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActivatesAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activates_at");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset?>("RetiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retires_at");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "ActivatesAt");

                    b.ToTable("evidence_codes", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Evidence.ReviewAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("action");

                    b.Property<string>("AfterSnapshot")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_snapshot");

                    b.Property<string>("BeforeSnapshot")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_snapshot");

                    b.Property<string>("Note")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("PerformedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at");

                    b.Property<Guid>("PerformedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("performed_by_account_id");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId", "PerformedAt");

                    b.ToTable("review_actions", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Evidence.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ApprovedContribution")
                        .HasColumnType("integer")
                        .HasColumnName("approved_contribution");

                    b.Property<Guid>("BoardTileId")
                        .HasColumnType("uuid")
                        .HasColumnName("board_tile_id");

                    b.Property<string>("CaptainNote")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("captain_note");

                    b.Property<int>("ClaimedWeight")
                        .HasColumnType("integer")
                        .HasColumnName("claimed_weight");

                    b.Property<Guid>("CreditedParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("credited_participant_id");

                    b.Property<string>("CurrentReviewerNote")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("current_reviewer_note");

                    b.Property<Guid?>("DropSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("drop_snapshot_id");

                    b.Property<Guid?>("DuplicateOfSubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("duplicate_of_submission_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("ExpectedEvidenceCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("expected_evidence_code");

                    b.Property<bool>("PublicEvidenceHidden")
                        .HasColumnType("boolean")
                        .HasColumnName("public_evidence_hidden");

                    b.Property<bool>("PublicPlayerHidden")
                        .HasColumnType("boolean")
                        .HasColumnName("public_player_hidden");

                    b.Property<bool>("PublicPrivacyRequested")
                        .HasColumnType("boolean")
                        .HasColumnName("public_privacy_requested");

                    b.Property<Guid>("RequirementId")
                        .HasColumnType("uuid")
                        .HasColumnName("requirement_id");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid>("SubmittedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by_account_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "SubmittedAt");

                    b.HasIndex("EventId", "Status", "SubmittedAt");

                    b.ToTable("submissions", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Evidence.SubmissionContribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<Guid>("CreditedParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("credited_participant_id");

                    b.Property<Guid?>("DropSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("drop_snapshot_id");

                    b.Property<Guid>("RequirementId")
                        .HasColumnType("uuid")
                        .HasColumnName("requirement_id");

                    b.Property<DateTimeOffset?>("ReversedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reversed_at");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId")
                        .IsUnique();

                    b.HasIndex("TeamId", "RequirementId", "ReversedAt");

                    b.ToTable("submission_contributions", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Signups.EventParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("admin_notes");

                    b.Property<bool>("CaptainVolunteer")
                        .HasColumnType("boolean")
                        .HasColumnName("captain_volunteer");

                    b.Property<string>("Comments")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("comments");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<string>("DiscordIdentity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("discord_identity");

                    b.Property<decimal>("EhbSnapshot")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("ehb_snapshot");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("FormVersion")
                        .HasColumnType("integer")
                        .HasColumnName("form_version");

                    b.Property<string>("NormalizedPrimaryAccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_primary_account_name");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("payment_status");

                    b.Property<string>("PrimaryAccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("primary_account_name");

                    b.Property<string>("PrivateEditTokenHash")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("private_edit_token_hash");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<string>("SecondAccountName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("second_account_name");

                    b.Property<DateTimeOffset>("SignedUpAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signed_up_at");

                    b.Property<long>("SignupSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("signup_sequence");

                    b.Property<string>("SignupStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("signup_status");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("status_reason");

                    b.Property<DateTimeOffset?>("WaitingListedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("waiting_listed_at");

                    b.Property<DateTimeOffset?>("WithdrawnAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("withdrawn_at");

                    b.HasKey("Id");

                    b.HasIndex("PrivateEditTokenHash")
                        .IsUnique();

                    b.HasIndex("EventId", "NormalizedPrimaryAccountName");

                    b.HasIndex("EventId", "SignupSequence")
                        .IsUnique();

                    b.ToTable("event_participants", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Signups.SignupAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EventParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_participant_id");

                    b.Property<string>("QuestionLabelSnapshot")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("question_label_snapshot");

                    b.Property<Guid>("SignupQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("signup_question_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("EventParticipantId", "SignupQuestionId")
                        .IsUnique();

                    b.ToTable("signup_answers", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Signups.SignupQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("HelpText")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("help_text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("label");

                    b.Property<string>("Options")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("options");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean")
                        .HasColumnName("required");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "Key")
                        .IsUnique();

                    b.ToTable("signup_questions", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Teams.DraftPick", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DraftSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("draft_session_id");

                    b.Property<Guid>("EventParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_participant_id");

                    b.Property<int>("PickNumber")
                        .HasColumnType("integer")
                        .HasColumnName("pick_number");

                    b.Property<DateTimeOffset>("PickedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("picked_at");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer")
                        .HasColumnName("round_number");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTimeOffset?>("UndoneAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("undone_at");

                    b.HasKey("Id");

                    b.HasIndex("EventParticipantId")
                        .IsUnique()
                        .HasFilter("undone_at IS NULL");

                    b.HasIndex("DraftSessionId", "PickNumber")
                        .IsUnique()
                        .HasFilter("undone_at IS NULL");

                    b.ToTable("draft_picks", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Teams.DraftSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ControlVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("control_version");

                    b.Property<Guid?>("ControllerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("controller_account_id");

                    b.Property<DateTimeOffset?>("ControllerLeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("controller_lease_expires_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalized_at");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<int>("TargetTeamSize")
                        .HasColumnType("integer")
                        .HasColumnName("target_team_size");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("draft_sessions", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Teams.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("AffiliationName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("affiliation_name");

                    b.Property<int?>("DraftPosition")
                        .HasColumnType("integer")
                        .HasColumnName("draft_position");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalized_at");

                    b.Property<string>("FormationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("formation_type");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IncludedInDraft")
                        .HasColumnType("boolean")
                        .HasColumnName("included_in_draft");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "Slug")
                        .IsUnique();

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Teams.TeamMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedByDraftPickId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by_draft_pick_id");

                    b.Property<string>("AssignmentReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("assignment_reason");

                    b.Property<Guid>("EventParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_participant_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<DateTimeOffset?>("LeftAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("left_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("EventParticipantId")
                        .IsUnique()
                        .HasFilter("left_at IS NULL");

                    b.HasIndex("TeamId", "EventParticipantId");

                    b.ToTable("team_memberships", (string)null);
                });

            modelBuilder.Entity("Bingo.Infrastructure.Persistence.SystemMetadata", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("system_metadata", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
