#!/usr/bin/env python3
"""Builds the Integration shard timing file from CI TRX results.

    python3 .github/scripts/integration-timings-from-trx.py integration-*.trx \
        > .github/scripts/integration-test-timings.tsv

A class weighs its observed elapsed envelope (last case end minus first case
start). A method whose summed case durations reach ISOLATE_SECONDS gets its own
row, so the partition can run it on its own shard; its class row then weighs
the rest of the class.
"""
import re
import sys
import xml.etree.ElementTree as ET
from collections import defaultdict
from datetime import datetime

ISOLATE_SECONDS = 60
PREFIX = "Bingo.IntegrationTests."
NS = {"t": "http://microsoft.com/schemas/VisualStudio/TeamTest/2010"}


def instant(value):
    return datetime.fromisoformat(re.sub(r"(\.\d{6})\d*", r"\1", value))


def seconds(value):
    hours, minutes, rest = value.split(":")
    return int(hours) * 3600 + int(minutes) * 60 + float(rest)


def main(paths):
    if not paths:
        sys.exit("Pass one or more Integration TRX files.")
    start, end = {}, {}
    method_seconds = defaultdict(float)
    for path in paths:
        root = ET.parse(path).getroot()
        names = {}
        for test in root.iterfind(".//t:UnitTest", NS):
            method = test.find("t:TestMethod", NS)
            names[test.get("id")] = (method.get("className").removeprefix(PREFIX), method.get("name"))
        for result in root.iterfind(".//t:UnitTestResult", NS):
            class_name, method = names[result.get("testId")]
            first, last = instant(result.get("startTime")), instant(result.get("endTime"))
            start[class_name] = min(start.get(class_name, first), first)
            end[class_name] = max(end.get(class_name, last), last)
            method_seconds[(class_name, method)] += seconds(result.get("duration", "0:0:0"))

    isolated = {key: value for key, value in method_seconds.items() if value >= ISOLATE_SECONDS}
    print("# Integration shard weights in seconds; see partition-integration-tests.sh.")
    print(f"# Generated by integration-timings-from-trx.py from {len(paths)} TRX file(s).")
    for class_name in sorted(start):
        envelope = (end[class_name] - start[class_name]).total_seconds()
        rest = envelope - sum(value for (owner, _), value in isolated.items() if owner == class_name)
        print(f"{class_name}\t{max(1, round(rest))}")
        for (owner, method), value in sorted(isolated.items()):
            if owner == class_name:
                print(f"{class_name}.{method}\t{round(value)}")


if __name__ == "__main__":
    main(sys.argv[1:])
