// Generated from the Board page modules: every literal passed to t(...). Keep in sync
// (board-page.test.js checks it). Danish lives in SharedResource.da.resx.
namespace Bingo.Web.Pages.Admin.Events;

public sealed partial class BoardModel
{
    public static readonly string[] LabelKeys =
    [
        "This event is read-only in its current lifecycle state.",
        "We couldn’t confirm that this happened.",
        "The board below is the current state; it didn’t change as asked. Check it before trying again.",
        "That change wasn’t saved.",
        "Approved {0}. Any tile, position or size change returns it to draft.",
        "Published {0}. Players see this board.",
        "Players see the version published {0} until you publish this correction.",
        "Resize",
        "{0} of {1} tiles",
        "Preview",
        "More board actions",
        "You’re editing",
        "Stop",
        "Editing control renews while you work and lapses after five minutes without board activity.",
        "{0} is editing",
        "Another administrator",
        "Take over…",
        "You can view everything. Their control lapses after five minutes without board activity.",
        "Viewing",
        "Start editing",
        "Start editing to change the board.",
        "Start editing first",
        "Board size…",
        "start editing",
        "stop editing",
        "Take over editing?",
        "{0} returns to viewing. Anything they haven’t saved stays in their browser; nothing on the board changes.",
        "Take over",
        "Cancel",
        "take over editing",
        "Checking…",
        "We couldn’t confirm whether this went through: {0}.",
        "Check before trying again, so nothing happens twice.",
        "Check again",
        "No board recorded.",
        "This event ended without a board, so there is nothing to show or change here.",
        "Read-only.",
        "This event is {0}, so its board can be viewed but not changed.",
        "Private correction.",
        "Reason: {0}",
        "Objectives with submitted evidence keep their requirements and scoring; wording can change. Changed tiles are marked with a dot.",
        "Row {0}",
        "Column {0}",
        "{0} EHB so far, incomplete",
        "no tiles yet",
        "Incomplete line",
        "{0}% above the average line",
        "{0}% below the average line",
        "{0}% above the average line ({1} EHB)",
        "{0}% below the average line ({1} EHB)",
        "Average line {0} EHB",
        "Board {0} rows by {1} columns",
        "No estimate",
        "Manual",
        "Manual EHB replaces the calculated estimate",
        "Manual challenge",
        "{0} parts",
        "{0} objectives, all required",
        "{0} needs catalogue verification. Review the affected choices or restore the missing catalogue mapping before approval.",
        "no estimate",
        "manual",
        "{0} objectives",
        "evidence submitted",
        "changed in this correction",
        "moving",
        "press Enter to swap here",
        "Enter to edit, M to move",
        "Enter to view",
        "Add tile",
        "Empty",
        "empty",
        "press Enter to move here",
        "Enter to add a tile",
        "Line totals in EHB",
        "Arrow keys move between positions. Enter edits a tile or adds one; M picks a tile up to move or swap it (or drag it), Delete removes it. Row and column totals are in EHB; ↑ and ↓ mark lines 25% or more from the average.",
        "Arrow keys move between positions; Enter opens a tile. Row and column totals are in EHB.",
        "Moving {0} from {1}. Choose a position with the arrow keys and press Enter; Escape cancels.",
        "swap {0} and {1}",
        "move {0} to {1}",
        "Swapped {0} and {1}.",
        "Moved to {0}.",
        "Not set",
        "Saving",
        "Saved",
        "over {0} days",
        "Players per team can only be changed before the event goes Live.",
        "An estimate for the planning figures. It doesn’t change rosters or scoring.",
        "Tiles",
        "{0} of {1}",
        "Average tile",
        "Lowest line",
        "Highest line",
        "Without an estimate",
        "{0} tile",
        "{0} tiles",
        "None",
        "Event length",
        "{0} days",
        "Enter a whole number from 1 to 100.",
        "change players per team",
        "Board size",
        "Rows and columns from 1 to 8. Tiles keep their positions.",
        "This is the current size.",
        "Move or remove these tiles first; they’re outside {0} × {1}:",
        "{0} × {1} has {2} positions; {3} tiles keep their positions.",
        "The board returns to draft.",
        "Applying…",
        "Apply size",
        "Board resized to {0} × {1}.",
        "resize the board to {0} × {1}",
        "Close preview",
        "Not supported yet",
        "Draft · private",
        "Approved · private",
        "Published",
        "Correction · private",
        "Cancelled",
        "Finalized",
        "Archived",
        "Rows",
        "Fewer rows",
        "More rows",
        "Columns",
        "Fewer columns",
        "More columns",
        "Preview · current draft values · nothing is approved or published",
        "Preview · the approved version · not published",
        "Preview · what players see now",
        "Preview · your private correction · players still see the published version",
    ];
}
