// Generated from the Board page modules: every literal passed to t(...). Keep in sync
// (board-page.test.js checks it). Danish lives in SharedResource.da.resx.
namespace Bingo.Web.Pages.Admin.Events;

public sealed partial class BoardModel
{
    // Labels that collide case-insensitively with another resource name; their Danish
    // (and English) entries are "AdminDesign." + key (Board.cshtml resolves them).
    public static readonly HashSet<string> ScopedLabelKeys = new(StringComparer.Ordinal)
    {
        "time", "optional", "Rows", "empty", "drops", "drop", "required", "take over editing",
        "remove {0}", "counts as", "start editing", "no estimate", "manual", "Evidence submitted",
    };

    public static readonly string[] LabelKeys =
    [
        "This event is read-only in its current lifecycle state.",
        "We couldn’t confirm that this happened.",
        "The board below is the current state; it didn’t change as asked. Check it before trying again.",
        "That change wasn’t saved.",
        "Approved {0}. Any tile, position or size change returns it to draft.",
        "Published {0}. Players see this board.",
        "Players see the version published {0} until you publish this correction.",
        "Resize",
        "{0} of {1} tiles",
        "Preview",
        "More board actions",
        "You’re editing",
        "Stop",
        "Editing control renews while you work and lapses after five minutes without board activity.",
        "{0} is editing",
        "Another administrator",
        "Take over…",
        "You can view everything. Their control lapses after five minutes without board activity.",
        "Viewing",
        "Start editing",
        "Start editing to change the board.",
        "Start editing first",
        "Board size…",
        "start editing",
        "stop editing",
        "Take over editing?",
        "{0} returns to viewing. Anything they haven’t saved stays in their browser; nothing on the board changes.",
        "Take over",
        "Cancel",
        "take over editing",
        "Checking…",
        "We couldn’t confirm whether this went through: {0}.",
        "Check before trying again, so nothing happens twice.",
        "Check again",
        "No board recorded.",
        "This event ended without a board, so there is nothing to show or change here.",
        "Read-only.",
        "This event is {0}, so its board can be viewed but not changed.",
        "Private correction.",
        "Reason: {0}",
        "Objectives with submitted evidence keep their requirements and scoring; wording can change. Changed tiles are marked with a dot.",
        "Row {0}",
        "Column {0}",
        "{0} EHB so far, incomplete",
        "no tiles yet",
        "Incomplete line",
        "{0}% above the average line",
        "{0}% below the average line",
        "{0}% above the average line ({1} EHB)",
        "{0}% below the average line ({1} EHB)",
        "Average line {0} EHB",
        "Board {0} rows by {1} columns",
        "No estimate",
        "Manual",
        "Manual EHB replaces the calculated estimate",
        "Manual challenge",
        "{0} parts",
        "{0} objectives, all required",
        "{0} needs catalogue verification. Review the affected choices or restore the missing catalogue mapping before approval.",
        "no estimate",
        "manual",
        "{0} objectives",
        "evidence submitted",
        "changed in this correction",
        "moving",
        "press Enter to swap here",
        "Enter to edit, M to move",
        "Enter to view",
        "Add tile",
        "Empty",
        "empty",
        "press Enter to move here",
        "Enter to add a tile",
        "Line totals in EHB",
        "Arrow keys move between positions. Enter edits a tile or adds one; M picks a tile up to move or swap it (or drag it), Delete removes it. Row and column totals are in EHB; ↑ and ↓ mark lines 25% or more from the average.",
        "Arrow keys move between positions; Enter opens a tile. Row and column totals are in EHB.",
        "Moving {0} from {1}. Choose a position with the arrow keys and press Enter; Escape cancels.",
        "swap {0} and {1}",
        "move {0} to {1}",
        "Swapped {0} and {1}.",
        "Moved to {0}.",
        "Not set",
        "Saving",
        "Saved",
        "over {0} days",
        "Players per team can only be changed before the event goes Live.",
        "An estimate for the planning figures. It doesn’t change rosters or scoring.",
        "Tiles",
        "{0} of {1}",
        "Average tile",
        "Lowest line",
        "Highest line",
        "Without an estimate",
        "{0} tile",
        "{0} tiles",
        "None",
        "Event length",
        "{0} days",
        "Enter a whole number from 1 to 100.",
        "change players per team",
        "Board size",
        "Rows and columns from 1 to 8. Tiles keep their positions.",
        "This is the current size.",
        "Move or remove these tiles first; they’re outside {0} × {1}:",
        "{0} × {1} has {2} positions; {3} tiles keep their positions.",
        "The board returns to draft.",
        "Applying…",
        "Apply size",
        "Board resized to {0} × {1}.",
        "resize the board to {0} × {1}",
        "Close preview",
        "Not supported yet",
        "Draft · private",
        "Approved · private",
        "Published",
        "Correction · private",
        "Cancelled",
        "Finalized",
        "Archived",
        "Rows",
        "Fewer rows",
        "More rows",
        "Columns",
        "Fewer columns",
        "More columns",
        "Preview · current draft values · nothing is approved or published",
        "Preview · the approved version · not published",
        "Preview · what players see now",
        "Preview · your private correction · players still see the published version",
        "Use 80 characters or fewer.",
        "Write a description, or use the automatic one.",
        "Use 4,000 characters or fewer.",
        "Enter a whole number from 1 to 10,000.",
        "Choose at least one boss or activity.",
        "Choose at least one eligible drop.",
        "Each drop counts as a whole number from 1 to 10,000.",
        "Describe what must be completed.",
        "Enter an EHB estimate above 0 (up to 100,000).",
        "Enter an EHB above 0 (up to 100,000), or use the calculated estimate.",
        "That tile isn’t on this board.",
        "The link may be from another board size or an older version.",
        "Close",
        "Tile",
        "Tile saved.",
        "The board changed while this was open.",
        "Your changes are still here. Check the board, then save your version on the latest board.",
        "Use the latest board",
        "The tile wasn’t saved.",
        "Your changes are still here.",
        "Tile saved. The board confirms your changes.",
        "We couldn’t confirm the save.",
        "The board doesn’t show these changes. They’re still here; check the board before saving again.",
        "We couldn’t confirm whether the tile was saved.",
        "Your changes are still here. Check before saving again, so nothing is saved twice.",
        "Remove {0}?",
        "{0} becomes empty. The tile and its objectives are deleted from this board.",
        "The approved board returns to draft.",
        "Remove tile",
        "remove {0}",
        "Tile removed.",
        "Working copy",
        "New tile",
        "View only",
        "Read-only",
        "Evidence submitted",
        "This tile isn’t on the board any more.",
        "Couldn’t load the tile editor",
        "Another administrator may have removed or moved it. Nothing was changed.",
        "The catalogue choices didn’t load. Nothing was changed.",
        "Try again",
        "Reading the current board.",
        "{0} is editing now.",
        "Your changes are still here; take over editing to save them.",
        "Remove tile…",
        "Can’t be removed: evidence was submitted",
        "Unsaved changes",
        "Saving…",
        "Save tile",
        "Name",
        "Name this tile",
        "Shown on the board and to players. Leave blank to name it after the chosen bosses.",
        "Description",
        "Written automatically from the objectives when you save.",
        "Written automatically from the objectives.",
        "Write your own",
        "Your own wording. Players see it instead of the automatic description.",
        "Use automatic description",
        "Artwork",
        "optional",
        "Current tile artwork",
        "Replace",
        "Upload",
        "Choose a PNG, JPEG or WebP image up to 10 MB.",
        "Remove",
        "PNG, JPEG or WebP. Shown on the tile instead of the default artwork.",
        "Challenges",
        "Challenge",
        "Objectives",
        "Objective",
        "All {0} must be completed",
        "Objective kind",
        "Collect drops",
        "One kind per tile; switching keeps what you entered for the other kind until you save.",
        "Add another challenge",
        "Add another objective",
        "New manual objective",
        "New objective",
        "Collect {0}: {1}",
        "Objective {0}: ",
        "Evidence submitted: requirements locked",
        "Locked by submitted evidence",
        "Remove objective {0}",
        "Remove objective",
        "Evidence has been submitted for this objective, so what it requires and how it counts can’t change.",
        "Collect",
        "drop",
        "drops",
        "of the chosen drops",
        "The same drop can count again",
        "Each chosen drop counts once",
        "{0} drop counts extra",
        "{0} drops count extra",
        "every drop counts as 1",
        "Done",
        "Change",
        "The same drop can count more than once",
        "Off: each chosen drop counts once, so the target needs that many different drops.",
        "Some drops count as more than one",
        "Set how much each chosen drop counts toward the target, for example a rare drop counting as 2.",
        "What must be completed?",
        "e.g. Complete a four-player Theatre of Blood in under 22:00",
        "Complete",
        "time",
        "times",
        "Each approved completion counts once. Evidence and approval are still required.",
        "Bosses or activities",
        "Chosen bosses or activities",
        "Unavailable boss",
        "Remove {0}",
        "Search the catalogue",
        "No boss or activity matches “{0}”.",
        "Eligible drops",
        "Choose a boss or activity to see its drops.",
        "{0} drops",
        "Clear",
        "Choose all",
        "No rate",
        "No drop rate in the catalogue",
        "counts as",
        "Unavailable item",
        "Missing a drop or rate?",
        "Open Catalogue",
        "in a new tab; your entries stay here.",
        "{0} has no drop rate in the catalogue.",
        "{0} has no kill rate in the catalogue, so {1} can’t be estimated.",
        "Estimate",
        "Effective",
        "none yet",
        "Calculated from catalogue rates",
        "Can’t calculate",
        "Calculated when you save",
        "Correct the rate in Catalogue",
        "A manual EHB can’t replace a missing rate; approval still needs it.",
        "Manual EHB for this tile",
        "Replaces the calculated estimate for this event’s tile only. Catalogue rates aren’t changed.",
        "Use calculated",
        "Uses the calculated estimate.",
        "Set EHB manually",
        "Estimated EHB",
        "required",
        "Manual challenges have no drop rates to calculate from, so enter the expected hours for one player.",
        "Evidence has been submitted for this tile, so its EHB is part of its scoring and can’t change.",
        "Saving any change returns the approved board to draft.",
        "Changes stay private until you publish the correction.",
        "Fill every board position",
        "({0} empty).",
        "needs automatic EHB: no drop rate in the catalogue for {0}. Correct the rate in Catalogue; a manual EHB can’t replace it.",
        "uses drops with no catalogue GP value. {0}",
        "Dismiss",
        "Ready to publish once:",
        "Open {0}",
        "Teams / Draft",
        "Finalize the team rosters first.",
        "The event has already started.",
        "The event’s end has passed.",
        "Reason",
        "e.g. Tile C4 named the wrong boss.",
        "Required. Kept in the board history.",
        "Enter a reason.",
        "Use 2,000 characters or fewer.",
        "Working…",
        "One thing needs fixing first.",
        "{0} things need fixing first.",
        "approve the board",
        "Board approved privately. Publishing is a separate step.",
        "return the board to draft",
        "Board returned to draft. The approval stays in its history.",
        "Publish the board?",
        "Players will see the approved {0} × {1} board for {2}.",
        "Publishing doesn’t start the event; it starts at its scheduled time or from Overview.",
        "After publishing, changes need a correction with a reason.",
        "Publish board",
        "publish the board",
        "Board published. Players can see it; the event starts separately.",
        "The board can’t be published yet.",
        "Correct the published board?",
        "This is for exceptional fixes. You edit a private copy; players keep the current board until you publish the correction.",
        "Objectives with submitted evidence keep their requirements and scoring; wording can change.",
        "Results, evidence and the published history stay as they are.",
        "Start correction",
        "start a correction",
        "Private correction started. Players still see the published board.",
        "No tiles differ from the published board.",
        "1 tile differs from the published board",
        "{0} tiles differ from the published board",
        "1 of them removed.",
        "{0} of them removed.",
        "Publish the correction?",
        "The corrected board is validated and replaces it for players.",
        "The earlier version stays in history; evidence and results aren’t rescored.",
        "Publish correction",
        "publish the correction",
        "Corrected board published. The earlier version stays in history.",
        "Discard the correction?",
        "All unpublished edits in this correction will be lost, and the working board returns to the published version.",
        "Published results and submitted evidence stay as they are.",
        "Discard correction",
        "discard the correction",
        "Correction discarded. The working board matches the published one again.",
        "Approving…",
        "Approve board",
        "Start editing to approve",
        "Publish board…",
        "Publish correction…",
        "Start editing to publish",
        "Return to draft",
        "Correct published board…",
        "Not available in this event state",
        "Discard correction…",
    ];
}
