const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium,webkit}=require('playwright'),{startFixture,login}=require('../../scripts/lib/admin-parity-fixture.cjs');
(async()=>{const engine=process.env.PLAYWRIGHT_BROWSER||'chromium',out=path.join(process.cwd(),'artifacts/schedule-signup-text-'+engine),fixture=await startFixture(process.cwd(),out),records=[];let browser;try{browser=await(engine==='webkit'?webkit:chromium).launch({headless:true});const context=await browser.newContext(),page=await login(context,fixture);
for(const language of['en','da']){await page.goto(fixture.origin+'/Admin/Events/SignupSetup/'+fixture.events['autumn-bingo-2027']);if(language==='da'){await page.locator('[name=culture][value=da]').click();await page.waitForFunction(()=>document.documentElement.lang==='da');}await page.locator('#add-custom').waitFor({state:'attached'});const state=JSON.parse(await page.locator('[data-signup-setup]').getAttribute('data-current'));if(!state.settings.participantCap){await page.locator('#cap-input').fill(String(Math.max(20,state.confirmed)));await page.locator('#cap-save').click();await page.waitForFunction(()=>JSON.parse(document.querySelector('[data-signup-setup]').dataset.current).settings.participantCap); }await page.waitForFunction(()=>document.querySelector('[data-confirmed]').textContent.includes(document.documentElement.lang==='da'?' af ':' of '));const count=await page.locator('[data-confirmed]').innerText();assert.match(count,language==='da'?/^\d+ af \d+$/:/^\d+ of \d+$/);assert.equal(await page.locator('.ss-counts .fact-label').first().innerText(),language==='da'?'Bekræftet':'Confirmed');
for(const width of[390,494,860,1280,1440]){await page.setViewportSize({width,height:900});const g=await page.locator('#cap-input').evaluate(e=>({width:e.getBoundingClientRect().width,max:getComputedStyle(e).maxWidth,parent:e.parentElement.getBoundingClientRect().width}));assert.equal(g.max,width<=640?'none':'180px');assert.ok(Math.abs(g.width-(width<=640?g.parent:Math.min(180,g.parent)))<.1);records.push({language,width,input:g,count});}
for(const key of['autumn-bingo-2027','clan-cup-pvm-week','midsummer-skilling-sprint','spring-finalized','spring-cancelled']){await page.goto(fixture.origin+'/Admin/Events/Schedule/'+fixture.events[key]);await page.waitForFunction(()=>window.AdminUI);await page.evaluate(async()=>{await import(document.querySelector('script[data-admin-page-script]').src);});const texts=await page.locator('.ro-value,.field-lock,[data-uploads-close]').allTextContents();const dates=texts.filter(t=>/\d{4}/.test(t));assert.ok(dates.length,key+': date texts present');for(const text of dates){assert.doesNotMatch(text,/\b0\d [\p{L}.]+ \d{4}/u);assert.match(text,/\b[1-9]\d? [\p{L}.]+ \d{4}, \d{2}:\d{2}/u);}
for(const input of await page.locator('.dtp-date').all()){const value=await input.inputValue();if(value){assert.match(value,/^[1-9]\d? [\p{L}.]+ \d{4}$/u);assert.equal(value.includes(language==='da'?'jun.':'Jun')||!value.toLowerCase().includes('jun'),true);}}
records.push({language,event:key,dates});}}
// First-response text is server formatted with the same contract; ISO transport remains untouched.
const signup=fs.readFileSync('src/Bingo.Web/Pages/Admin/Events/SignupSetup.cshtml.cs','utf8');assert.match(signup,/firstResponseDay.*ToString\("d MMM yyyy, HH':'mm", CultureInfo.CurrentCulture\)/);
console.log('PASS English/Danish counts, reference input width atfive sizes, Schedule date boxes/reasons/derived values in5 lifecycle states and Signup first-response format');
}finally{await browser?.close();await fixture.close();fs.writeFileSync(path.join(out,'checks.json'),JSON.stringify({engine,records},null,2));}})().catch(e=>{console.error(e);process.exitCode=1});
