const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium,webkit}=require('playwright'),{startFixture,login}=require('../../scripts/lib/admin-parity-fixture.cjs');
const registrations=require('../../scripts/lib/admin-page-conformance-pages.cjs'),{checkLoaded,checkDocument}=require('../../scripts/lib/admin-page-conformance-checks.cjs');
(async()=>{const engine=process.env.PLAYWRIGHT_BROWSER||'chromium',out=path.join(process.cwd(),'artifacts/readonly-values-'+engine),fixture=await startFixture(process.cwd(),out),records=[];let browser;try{browser=await(engine==='webkit'?webkit:chromium).launch({headless:true});const context=await browser.newContext(),page=await login(context,fixture);
for(const registration of registrations.filter(p=>['identity','schedule','signupsetup'].includes(p.family))){await page.goto(fixture.origin+registration.url(fixture).replace(fixture.events['autumn-bingo-2027'],fixture.events['spring-finalized']));await page.evaluate(async()=>{await import(document.querySelector('script[data-admin-page-script]').src);await document.fonts.ready;});for(const width of[390,494,860,1280,1440]){await page.setViewportSize({width,height:1000});await checkLoaded(page,{...registration,style:registration.readOnlyStyle||registration.style},width);await checkDocument(page,registration,width);const values=await page.evaluate(()=>[...document.querySelectorAll('.ro-value')].filter(e=>e.checkVisibility()).map(e=>{const c=getComputedStyle(e);return{text:e.textContent.trim(),height:e.getBoundingClientRect().height,minimum:parseFloat(c.getPropertyValue('--dk-control-h')),border:c.borderTopWidth,radius:c.borderRadius,background:c.backgroundColor,color:c.color};}));assert.ok(values.length,registration.family+' real read-only values');for(const value of values){assert.ok(value.height>=value.minimum-.1);assert.equal(value.border,'1px');}
const geometry=await page.evaluate(()=>{const host=document.createElement('div');host.id='readonly-probe';host.style.width='200px';host.innerHTML='<input class="input"><div class="dtp is-readonly"></div><div class="ro-value" id="ro-single">Value</div><div class="ro-value" id="ro-multi">One\nTwo\nThree</div><div class="ro-value is-empty">None</div>';document.querySelector('[data-page-region]>.page').append(host);const read=s=>{const e=host.querySelector(s),c=getComputedStyle(e);return{height:e.getBoundingClientRect().height,border:c.borderTopWidth,borderColor:c.borderTopColor,radius:c.borderRadius,background:c.backgroundColor,color:c.color};};return{input:read('input'),date:read('.dtp'),single:read('#ro-single'),multi:read('#ro-multi'),empty:read('.is-empty')};});assert.equal(geometry.single.height,geometry.input.height);assert.equal(geometry.single.border,geometry.input.border);assert.equal(geometry.single.radius,geometry.input.radius);assert.equal(geometry.single.background,geometry.date.background);assert.equal(geometry.single.borderColor,geometry.date.borderColor);assert.equal(geometry.single.color,geometry.input.color);assert.notEqual(geometry.empty.color,geometry.single.color);assert.ok(geometry.multi.height>geometry.single.height);await page.locator('#ro-single').hover();const hovered=await page.locator('#ro-single').evaluate(e=>{const c=getComputedStyle(e);return{background:c.backgroundColor,border:c.borderTopColor};});assert.equal(hovered.background,geometry.single.background);assert.equal(hovered.border,geometry.single.borderColor);await page.locator('#readonly-probe').evaluate(e=>e.remove());records.push({family:registration.family,width,values,geometry});console.log('PASS readonly '+registration.family+' '+width);}}
// The shared drawer consumes the same value rule; no persistence mutation needed.
await page.goto(fixture.origin+registrations.find(p=>p.family==='signupsetup').url(fixture));await page.locator('#tab-form').click();await page.locator('#add-custom').click();await page.locator('.drawer').waitFor();await page.locator('[data-type-value]').evaluate(e=>{e.textContent='Single choice';e.parentElement.hidden=false;});const drawer=await page.locator('[data-type-value]').evaluate(e=>{const c=getComputedStyle(e);return{height:e.getBoundingClientRect().height,minimum:parseFloat(c.getPropertyValue('--dk-control-h')),border:c.borderTopWidth};});assert.equal(drawer.height,drawer.minimum);assert.equal(drawer.border,'1px');console.log('PASS shared drawer readonly value');
}finally{await browser?.close();await fixture.close();fs.writeFileSync(path.join(out,'checks.json'),JSON.stringify({engine,records},null,2));}})().catch(e=>{console.error(e);process.exitCode=1});
