// U9: RC09 W1-W6, WA-9, AU20, A15, C-CMP-2. Owned PostgreSQL/Kestrel only.
const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const {chromium,webkit}=require('playwright');
const {startFixture,login}=require('../../scripts/lib/admin-parity-fixture.cjs');
(async()=>{
 const engine=process.env.PLAYWRIGHT_BROWSER||'chromium',output=path.join(process.cwd(),'artifacts/wom-'+engine),cases=[];
 const browser=await(engine==='webkit'?webkit:chromium).launch({headless:true});
 async function scenario(variant,body){
  if(process.env.U9_WOM_VARIANTS&&!process.env.U9_WOM_VARIANTS.split(',').includes(variant))return;
  const fixture=await startFixture(process.cwd(),path.join(output,variant),{BINGO_PARITY_UR_PROFILE:variant==='rate-limited'||variant==='fetch-ready'?'live':'final-review',BINGO_PARITY_U9_WOM:variant});
  const context=await browser.newContext({viewport:{width:1280,height:1000}});
  try{const page=await login(context,fixture),errors=[];page.on('pageerror',error=>errors.push(error.message));page.on('dialog',dialog=>dialog.accept());
   const route=slug=>'/Admin/Events/WiseOldMan/'+fixture.events[slug],go=async slug=>{await page.goto(fixture.origin+route(slug));await page.waitForFunction(()=>window.AdminUI&&document.querySelector('[data-wom]'));};
   const state=()=>page.locator('[data-wom]').getAttribute('data-current').then(JSON.parse),accept=()=>page.locator('.modal [data-confirm-accept]'),notice=()=>page.locator('[data-wom-notice]');
   await body({page,fixture,route,go,state,accept,notice});assert.deepEqual(errors,[]);console.log('PASS WOM '+variant+' ['+engine+']');
  }finally{await context.close();await fixture.close();}
 }
 try{
 await scenario('base',async({page,fixture,route,go,state,accept,notice})=>{
  await go('ur-current');assert.match(await page.locator('#sync-state').textContent(),/pending/i);assert.equal(await page.locator('#fetch-btn').isDisabled(),true);assert.match(await page.locator('[data-wom]').textContent(),/paused/i);assert.equal((await state()).activity.expectedAccountCount,6);assert.doesNotMatch(await page.locator('.wm-empty .empty-title').textContent(),/No teams yet/);await page.screenshot({path:path.join(output,'pending-wide.png'),fullPage:true,animations:'disabled'});await page.setViewportSize({width:390,height:900});await page.screenshot({path:path.join(output,'pending-phone.png'),fullPage:true,animations:'disabled'});await page.setViewportSize({width:1280,height:1000});
  await go('ur-wom-unavailable');assert.match(await page.locator('#sync-state').textContent(),/could not/i);assert.equal(await page.locator('[data-wom-action] button:enabled').count(),0);
  await go('ur-cancelled');assert.match(await page.locator('[data-wom]').textContent(),/cancelled/i);assert.equal(await page.locator('[data-wom-action] button:enabled').count(),0);cases.push('A15 / C-CMP-1: Pending pauses fetch, retained could-not-update and Cancelled remain read-only');
  for(const slug of ['ur-upcoming-02','ur-upcoming-03']){await go(slug);assert.equal((await state()).management.canCreate,false);assert.equal(await page.locator('#link-btn').isDisabled(),true);assert.match(await page.locator('[data-wom]').textContent(),/queued|unconfirmed|unknown/i);}
  await go('ur-upcoming-04');assert.match(await page.locator('[data-wom]').textContent(),/Unknown origin; contact an operator/);assert.equal(await page.locator('#delete-btn').count(),0);cases.push('WA-9 / C-WOM-3: queued and unknown operations lock Create/Link; Unknown origin stays locked');
  await go('ur-signups-open');assert.equal((await state()).integration.canDisconnect,true);assert.equal(await page.locator('#delete-btn').count(),0);await page.locator('#relink-btn').click();await page.locator('#wom-link-id').fill('');await accept().click();assert.match(await page.locator('.modal [role=alert]').textContent(),/valid competition ID/);await page.locator('#wom-link-id').fill('93501');await page.reload();await page.locator('#relink-btn').click();assert.equal(await page.locator('#wom-link-id').inputValue(),'93501');assert.equal(await page.locator('.scroller.is-locked').count(),1);
  await page.route('**'+route('ur-signups-open')+'?handler=Competition',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({succeeded:false,outcome:'refused',error:'The event changed. Review the latest state.'})}));await accept().click();await page.waitForFunction(()=>document.querySelector('.modal [role=alert]')?.textContent.includes('event changed'));assert.equal(await page.locator('#wom-link-id').inputValue(),'93501');await page.unroute('**'+route('ur-signups-open')+'?handler=Competition');await page.reload();cases.push('RC09 W4/W6 / AU20: link validation, refusal and reload retain event-scoped ID; shared modal locks scroll');
  await page.locator('[data-wom-action=code] button').click();await page.locator('#wom-code').fill('synthetic-unsent-code');await page.reload();await page.locator('[data-wom-action=code] button').click();assert.equal(await page.locator('#wom-code').inputValue(),'synthetic-unsent-code');
  await page.route('**'+route('ur-signups-open')+'?handler=AdoptCompetitionCredential',r=>r.fulfill({status:200,headers:{'Content-Type':'text/html','X-Bingo-Post-Navigation':'/Account/Login'},body:'<html>Sign in</html>'}));await accept().click();await page.getByRole('heading',{name:'Your changes were not saved'}).waitFor();assert.doesNotMatch(await page.locator('.modal .kv').textContent(),/synthetic-unsent-code/);assert.match(await page.locator('.modal .kv').textContent(),/submitted code was cleared/);await page.getByRole('button',{name:'Keep editing',exact:true}).click();assert.equal(await page.locator('#wom-code').inputValue(),'');assert.doesNotMatch(await page.evaluate(()=>JSON.stringify(sessionStorage)),/synthetic-unsent-code/);await page.unroute('**'+route('ur-signups-open')+'?handler=AdoptCompetitionCredential');
  await page.locator('#wom-code').fill('synthetic-new-code');await accept().click();await page.waitForFunction(()=>!document.querySelector('.modal')&&document.querySelector('[data-wom-notice]')?.textContent.trim());assert.match(await notice().textContent(),/stored protected/);assert.equal((await state()).management.canWrite,true);cases.push('C-CMP-2 / RC09 W4 / AU20: unsent code persists; submitted code clears before session-loss UI; real adopt stores protected capability');
  await page.locator('[data-wom-action=code] button').click();await page.locator('#wom-code').fill('synthetic-unknown-code');await page.route('**'+route('ur-signups-open')+'?handler=AdoptCompetitionCredential',r=>r.fulfill({status:502,body:'response lost'}));await accept().click();await page.locator('[data-wom-readback]').first().waitFor();assert.match(await page.locator('#sync-state').textContent(),/unconfirmed/i);await page.route('**'+route('ur-signups-open')+'?handler=Current',r=>r.fulfill({status:503,body:'read unavailable'}));await page.locator('[data-wom-readback]').first().click();await page.waitForFunction(()=>document.querySelector('[data-wom-notice]')?.textContent.includes('current state is unavailable'));assert.match(await page.locator('#sync-state').textContent(),/unconfirmed/i);await page.unroute('**'+route('ur-signups-open')+'?handler=Current');await page.locator('[data-wom-readback]').first().click();await page.waitForFunction(()=>document.querySelector('[data-wom-notice]')?.textContent.includes('Current stored connection:'));assert.match(await page.locator('#sync-state').textContent(),/unconfirmed/i);await page.unroute('**'+route('ur-signups-open')+'?handler=AdoptCompetitionCredential');cases.push('RC09 W3/W5: failed readback stays unknown; cached writable connection never claims an unknown update is up to date');
  await page.locator('#disconnect-btn').click();await page.locator('#wom-reason').fill('Controlled replacement');await page.reload();await page.locator('#disconnect-btn').click();assert.equal(await page.locator('#wom-reason').inputValue(),'Controlled replacement');
  let held;await page.route('**'+route('ur-signups-open')+'?handler=DisconnectCompetition',r=>new Promise(resolve=>held=async()=>{await r.fetch({maxRedirects:0});await r.fulfill({status:502,body:'response lost'});resolve();}));await accept().click();await page.waitForFunction(()=>document.querySelector('.modal')?.getAttribute('aria-busy')==='true');assert.equal(await page.evaluate(()=>AdminUI.guard()),false);assert.equal(await page.evaluate(()=>{const event=new Event('beforeunload',{cancelable:true});window.dispatchEvent(event);return event.defaultPrevented;}),true);while(!held)await new Promise(resolve=>setTimeout(resolve,10));await held();await page.locator('[data-wom-readback]').first().waitFor();await page.reload();await page.locator('[data-wom-readback]').first().click();await page.waitForFunction(()=>document.querySelector('[data-wom-notice]')?.textContent.includes('Current stored connection:'));assert.equal((await state()).integration.competitionId,null);assert.match(await notice().textContent(),/couldn’t confirm.*Not connected/is);await page.unroute('**'+route('ur-signups-open')+'?handler=DisconnectCompetition');cases.push('RC09 W2/W4/W5 / AU20: real disconnect with lost response guards pending, survives reload, honestly reads local connection without attribution');
  await go('ur-upcoming-01');assert.doesNotMatch(await notice().textContent(),/couldn’t confirm/);assert.equal(await page.locator('#delete-btn').isEnabled(),true);await page.locator('#delete-btn').click();const deletion=page.waitForResponse(response=>response.url().includes('handler=DeleteManagedCompetition'));await accept().click();const deleted=await(await deletion).json();assert.equal(deleted.succeeded,false);assert.equal(deleted.outcome,'queued');assert.equal(deleted.status,'Retry');await page.waitForFunction(()=>!document.querySelector('.modal')&&document.querySelector('[data-wom-notice]')?.textContent.trim());assert.match(await notice().textContent(),/queued/i);assert.equal((await state()).management.operationType,3);assert.equal(await page.locator('#delete-btn').isDisabled(),true);cases.push('RC09 W1/W2 / WA-9: Website-managed delete queues once in place and cannot land on the previous event');
  await go('ur-signups-closed');assert.equal((await state()).management.canCreate,true,JSON.stringify((await state()).management.preview.errors));await page.locator('#create-btn').click();assert.ok(await page.locator('.modal [data-create-checks] li').count()>=3);await accept().click();await page.waitForFunction(()=>!document.querySelector('.modal')&&document.querySelector('[data-wom-notice]')?.textContent.trim());assert.match(await notice().textContent(),/queued/i);assert.equal((await state()).management.operationType,1);assert.equal(await page.locator('#link-btn').isDisabled(),true);cases.push('C-WOM-2 / WA-9: Create confirmation retains all three checks and real queued Create locks further links');
 });
 await scenario('rejected',async({page,go})=>{await go('ur-current');assert.match(await page.locator('#sync-state').textContent(),/rejected/i);assert.equal(await page.locator('#fetch-btn').isDisabled(),true);assert.match(await page.locator('[data-wom]').textContent(),/Target end/);cases.push('A15: mutable Rejected end update retains target and pauses fetch');});
 await scenario('rate-limited',async({page,fixture,go})=>{await go('ur-current');assert.equal(await page.locator('#fetch-btn').isDisabled(),true);assert.match(await page.locator('[data-wom]').textContent(),/rate limit|retry/i);await page.goto(fixture.origin+'/Admin/Events/Finalize/'+fixture.events['ur-archived']);await page.locator('#reopen-btn').waitFor();assert.equal(await page.locator('#reopen-btn').isDisabled(),true);assert.match(await page.locator('#reopen-why').textContent(),/is still live.*publish its results/is);cases.push('U9-Q1: Live current event blocks Final Review Reopen with the ruled guidance');cases.push('U9-Q2 / WA-6: rate-limited next retry shown without a generic cooldown');});
 await scenario('fetch-ready',async({page,route,go,state,notice})=>{
  await go('ur-current');assert.equal(await page.locator('#fetch-btn').isEnabled(),true);const before=(await state()).integration.lastSuccessfulAt;
  await page.route('**'+route('ur-current')+'?handler=FetchCompetition',r=>r.fulfill({status:502,body:'response lost'}));await page.locator('#fetch-btn').click();await page.locator('[data-wom-readback]').waitFor();await page.locator('[data-wom-readback]').click();await page.waitForFunction(()=>document.querySelector('[data-wom-notice]')?.textContent.includes('Current stored connection:'));assert.equal((await state()).integration.lastSuccessfulAt,before);assert.match(await notice().textContent(),/couldn’t confirm whether new data was fetched.*Last successful fetch on record/is);await page.unroute('**'+route('ur-current')+'?handler=FetchCompetition');
  await page.route('**'+route('ur-current')+'?handler=FetchCompetition',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({succeeded:false,outcome:'skipped',skipReason:'WithinHour',message:'The last successful fetch was less than an hour ago.',retryAt:'2027-06-02T13:00:00Z'})}));await page.locator('#fetch-btn').click();await page.waitForFunction(()=>document.querySelector('[data-wom-notice]')?.textContent.includes('less than an hour'));assert.match(await notice().textContent(),/Next eligible time/);cases.push('RC09 W3 / U9-Q2: old timestamp never proves timed-out fetch finished; exact skipped reason and eligible time render in place');
 });
 fs.writeFileSync(path.join(output,process.env.U9_WOM_VARIANTS?'focused-results.json':'results.json'),JSON.stringify({engine,cases},null,2));console.log('PASS '+cases.length+' WOM browser scenarios ['+engine+']');
 }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
