const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium,webkit}=require('playwright');
const {startFixture,login}=require('../../scripts/lib/admin-parity-fixture.cjs');
(async()=>{
 const engine=process.env.PLAYWRIGHT_BROWSER||'chromium',output=path.join(process.cwd(),'artifacts/schedule-'+engine),fixture=await startFixture(process.cwd(),output);let browser;const results=[],summaries=[];
 try{
  browser=await(engine==='webkit'?webkit:chromium).launch({headless:true});const context=await browser.newContext({viewport:{width:1280,height:900}}),page=await login(context,fixture),errors=[];page.on('pageerror',e=>{errors.push(e.message);});
  const route='/Admin/Events/Schedule/'+fixture.events['autumn-bingo-2027'];await page.goto(fixture.origin+route);await page.waitForFunction(()=>document.querySelector('#schedule-draftAt-time')?.value);
  const snapshot=()=>page.locator('[data-schedule-editor]').getAttribute('data-current').then(JSON.parse);
  const conversion=await page.evaluate(async()=>{const dtp=await import('/js/admin-date-time.js');return {skipped:dtp.localToUtc('2027-03-28T02:30','Europe/Copenhagen').status,ambiguous:dtp.localToUtc('2027-10-31T02:30','Europe/Copenhagen').status,summer:dtp.localToUtc('2027-06-20T19:05','Europe/Copenhagen'),roundtrip:dtp.utcToLocal(Date.parse('2027-06-20T17:05:00Z'),'Europe/Copenhagen')};});assert.equal(conversion.skipped,'invalid');assert.equal(conversion.ambiguous,'ambiguous');assert.equal(conversion.summer.ms,Date.parse('2027-06-20T17:05:00Z'));assert.equal(conversion.roundtrip,'2027-06-20T19:05');results.push('shared picker conversion rejects DST gaps/folds and round-trips event-local summer time');
  const before=await snapshot();assert.equal(before.phase,'SignupOpen');assert.equal(await page.locator('[data-schedule-editor]').getAttribute('data-published'),'true');
  await page.setViewportSize({width:390,height:342});await page.locator('#schedule-draftAt-btn').click();await page.locator('.dtp-pop').waitFor();
  await page.locator('.dtp-pop').evaluate(e=>Promise.all(e.getAnimations().map(a=>a.finished)));const popup=await page.locator('.dtp-pop').boundingBox();assert.ok(popup.y>=7&&popup.y+popup.height<=335,'picker fits short viewport: '+JSON.stringify(popup));
  await page.keyboard.press('ArrowRight');await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('.dtp-pop'));assert.equal(await page.locator('#schedule-draftAt-btn').evaluate(e=>e===document.activeElement),true);results.push('short viewport, keyboard day movement, Escape and focus restore');
  await page.setViewportSize({width:1280,height:900});
  await page.evaluate(()=>AdminUI.setUrl({probe:'history'},{probe:{default:'',valid:()=>true}},{record:true}));
  const historyUrl=page.url();await page.locator('#schedule-draftAt-btn').click();await page.locator('.dtp-pop').waitFor();await page.evaluate(()=>history.back());await page.waitForFunction(url=>location.href===url&&!document.querySelector('.dtp-pop'),historyUrl);await page.evaluate(()=>AdminUI.setUrl({},{probe:{default:'',valid:()=>true}}));results.push('Back closes the picker first and preserves the current route');
  await page.locator('#schedule-draftAt-time').fill('19:05');await page.locator('[data-identity-save]').click();
  await page.waitForFunction(old=>JSON.parse(document.querySelector('[data-schedule-editor]').dataset.current).version!==old,before.version);
  assert.equal(new URL(page.url()).pathname,route);const after=await snapshot();assert.equal(after.values.draftAt,'2027-06-20T17:05:00.0000000+00:00');results.push('real save stays on Schedule and commits canonical local draft time');
  await page.locator('#schedule-eventEndsAt-time').fill('22:05');await page.locator('[data-identity-save]').click();await page.locator('[data-confirm-title]').waitFor();assert.match(await page.locator('.compare').textContent(),/UTC\+02:00/);assert.match(await page.locator('.compare').textContent(),/Uploads close/);await page.locator('[data-confirm-cancel]').click();await page.locator('[data-confirm-title]').waitFor({state:'detached'});assert.equal(await page.locator('#schedule-eventEndsAt-time').inputValue(),'22:05');results.push('published comparison, UTC offsets, derived upload cutoff and cancellation retains entry');
  await page.locator('#schedule-eventEndsAt-time').fill('22:00');
  await page.locator('#schedule-draftAt-time').fill('19:10');assert.equal(await page.locator('input[name="Input.EventEndsLocal"]').inputValue(),'2027-07-06T22:00');assert.equal(await page.locator('input[name="Input.DraftLocal"]').inputValue(),'2027-06-20T19:10');
  await page.route('**'+route,async routed=>{if(routed.request().method()!=='POST')return routed.continue();await routed.fetch({maxRedirects:0});await routed.fulfill({status:502,contentType:'text/plain',body:'Synthetic lost save response'});});
  await page.locator('[data-identity-save]').click();await page.waitForFunction(()=>document.querySelector('[data-identity-save]')?.textContent.includes('Check again'));assert.equal(await page.locator('#schedule-draftAt-time').inputValue(),'19:10');await page.unroute('**'+route);
  await page.locator('[data-identity-save]').click();await page.waitForFunction(()=>document.querySelector('[data-schedule-feedback]')?.textContent.includes('now has the values'));assert.equal((await snapshot()).values.draftAt,'2027-06-20T17:10:00.0000000Z');results.push('applied response lost; immutable intent confirmed by GET, Up to date without saved attribution');
  // A second editor changes both a touched and an untouched field before this save.
  await page.locator('#schedule-draftAt-time').fill('19:15');
  const other=await context.newPage();await other.goto(fixture.origin+route);await other.waitForFunction(()=>document.querySelector('#schedule-draftAt-time')?.value);
  const concurrentBefore=await other.locator('[data-schedule-editor]').getAttribute('data-current').then(JSON.parse);
  await other.locator('#schedule-draftAt-time').fill('19:20');await other.locator('#schedule-eventEndsAt-time').fill('22:10');await other.locator('[data-identity-save]').click();await other.locator('[data-confirm-accept]').click();await other.waitForFunction(old=>JSON.parse(document.querySelector('[data-schedule-editor]').dataset.current).version!==old,concurrentBefore.version);
  await page.locator('[data-identity-save]').click();await page.getByRole('button',{name:'Use theirs',exact:true}).waitFor();assert.equal(await page.locator('#schedule-draftAt-time').inputValue(),'19:15');assert.equal(await page.locator('#schedule-eventEndsAt-time').inputValue(),'22:10');await page.getByRole('button',{name:'Use theirs',exact:true}).click();assert.equal(await page.locator('#schedule-draftAt-time').inputValue(),'19:20');await other.close();results.push('real stale version merges untouched fields and retains conflicting entry until Use theirs');
  await page.locator('#schedule-draftAt-time').fill('19:15');
  await page.route('**'+route,async routed=>{if(routed.request().method()!=='POST')return routed.continue();await routed.fulfill({status:200,headers:{'Content-Type':'text/html','X-Bingo-Post-Navigation':'/Account/Login'},body:'<html>Sign in</html>'});});
  await page.locator('[data-identity-save]').click();await page.getByRole('heading',{name:'Your changes were not saved'}).waitFor();assert.equal(await page.locator('#schedule-draftAt-time').inputValue(),'19:15');await page.getByRole('button',{name:'Keep editing',exact:true}).click();results.push('login redirect classified; unsent date/time draft retained');
  page.on('dialog',dialog=>dialog.accept());await page.goto(fixture.origin+'/Admin/Events/Schedule/'+fixture.events['midsummer-skilling-sprint']);await page.waitForFunction(()=>document.querySelector('#schedule-eventEndsAt-time')?.value);assert.equal(await page.locator('[data-date-time]').count(),1);
  await page.locator('#schedule-eventEndsAt-time').fill('22:05');await page.locator('[data-identity-save]').click();await page.locator('#schedule-end-reason').waitFor();await page.locator('[data-confirm-accept]').click();assert.equal(await page.locator('[data-reason-error]').isVisible(),true);await page.locator('#schedule-end-reason').fill('Synthetic browser end adjustment.');await page.locator('.m-scrim').last().click({position:{x:2,y:2}});await page.waitForFunction(()=>document.querySelectorAll('[data-confirm-title]').length===2);await page.locator('[data-confirm-cancel]').last().click();await page.waitForFunction(()=>document.querySelectorAll('[data-confirm-title]').length===1);assert.equal(await page.locator('#schedule-end-reason').inputValue(),'Synthetic browser end adjustment.');const liveBefore=await snapshot();await page.locator('[data-confirm-accept]').click();await page.waitForFunction(old=>JSON.parse(document.querySelector('[data-schedule-editor]').dataset.current).version!==old,liveBefore.version);results.push('Live end-only edit, required reason and successful confirmed save');
  await page.goto(fixture.origin+route);await page.waitForFunction(()=>document.querySelector('#schedule-draftAt-time')?.value);await page.evaluate(()=>document.fonts.ready);
  for(const language of ['en','da']){if(language==='da'){await page.locator('[name=culture][value=da]').click();await page.waitForFunction(()=>document.documentElement.lang==='da');}for(const width of [390,494,860,1280,1440]){await page.setViewportSize({width,height:900});await page.evaluate(async()=>{await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));await Promise.all(document.getAnimations().filter(a=>a.effect.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{})));});summaries.push(await page.locator('.page-head .summary').evaluate((el,args)=>({language:args.language,width:args.width,text:el.textContent.trim(),height:el.getBoundingClientRect().height,lineHeight:parseFloat(getComputedStyle(el).lineHeight),links:[...el.querySelectorAll('a')].map(a=>({text:a.textContent,url:a.pathname}))}),{language,width}));if(language==='en'&&(width===390||width===1280))await page.screenshot({path:path.join(output,'schedule-'+width+'.png')});}}
  results.push('English/Danish linked summary measured at all five widths');
  assert.deepEqual(errors,[]);console.log('PASS '+results.length+' Schedule interaction groups: '+results.join('; '));
 }finally{await browser?.close();await fixture.close();fs.writeFileSync(path.join(output,'checks.json'),JSON.stringify({engine,results,summaries},null,2));}
})().catch(e=>{console.error(e);process.exitCode=1;});
