// U9: RC08, A15, U9-Q1, C-CMP-2 against an owned PostgreSQL/Kestrel fixture.
const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const {chromium,webkit}=require('playwright');
const {startFixture,login}=require('../../scripts/lib/admin-parity-fixture.cjs');
(async()=>{
 const engine=process.env.PLAYWRIGHT_BROWSER||'chromium',output=path.join(process.cwd(),'artifacts/final-review-'+engine);
 const fixture=await startFixture(process.cwd(),output,{BINGO_PARITY_UR_PROFILE:'final-review',BINGO_PARITY_U9_READY:'1'});let browser;const cases=[];
 try{
  browser=await(engine==='webkit'?webkit:chromium).launch({headless:true});const context=await browser.newContext({viewport:{width:1280,height:1000}}),page=await login(context,fixture);const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
  const route='/Admin/Events/Finalize/'+fixture.events['ur-current'],current=()=>page.locator('[data-final-review]').getAttribute('data-current').then(JSON.parse),ready=()=>page.waitForFunction(()=>window.AdminUI&&document.querySelector('[data-final-review]'));
  await page.goto(fixture.origin+'/Admin/Events/Finalize/'+fixture.events['ur-archived']);await ready();assert.equal(await page.locator('#reopen-btn').isDisabled(),true);assert.match(await page.locator('#reopen-why').textContent(),/Publish the results of .* first/);assert.equal(await page.locator('#reopen-why a').textContent(),'Open event');cases.push('U9-Q1: Awaiting-review blocker disables Reopen and keeps fixed Open event link');
  await page.goto(fixture.origin+route);await ready();assert.equal((await current()).canFinalize,true);const cycle=(await current()).reviewCycleId;
  await page.locator('#publish-btn').click();await page.locator('.modal [data-confirm-accept]').waitFor();assert.match(await page.locator('.modal').textContent(),/Publishing now makes the last fetch before the end the official WOM data/);assert.equal(await page.locator('.modal .fr-top li').count(),2);
  let held;await page.route('**'+route+'?handler=Finalize',r=>new Promise(resolve=>held=async()=>{await r.fulfill({status:502,contentType:'text/plain',body:'response lost'});resolve();}));await page.locator('.modal [data-confirm-accept]').click();await page.waitForFunction(()=>document.querySelector('.modal')?.getAttribute('aria-busy')==='true');assert.equal(await page.evaluate(()=>{const event=new Event('beforeunload',{cancelable:true});window.dispatchEvent(event);return event.defaultPrevented;}),true);assert.equal(await page.evaluate(()=>AdminUI.guard()),false);assert.equal(await page.locator('.scroller.is-locked').count(),1);while(!held)await new Promise(resolve=>setTimeout(resolve,10));await held();await page.locator('[data-final-readback]').waitFor();cases.push('RC08 F2/F6: pending publish guards reload/navigation and modal locks page scrolling');assert.equal(await page.locator('#publish-btn').isDisabled(),true);
  await page.locator('[data-final-readback]').click();await page.waitForFunction(()=>document.querySelector('[data-final-notice]')?.textContent.includes('Current state:'));assert.match(await page.locator('[data-final-notice]').textContent(),/couldn’t confirm whether.*Current state: Final review/is);assert.equal((await current()).state,'AwaitingFinalReview');cases.push('RC08 F1: negative readback reports current state without asserting the request did not run');
  await page.unroute('**'+route+'?handler=Finalize');await page.locator('#publish-btn').click();
  await page.route('**'+route+'?handler=Finalize',async r=>{await r.fetch({maxRedirects:0});await r.fulfill({status:502,contentType:'text/plain',body:'response lost'});});
  await page.locator('.modal [data-confirm-accept]').click();await page.locator('[data-final-readback]').waitFor();await page.reload();await ready();await page.locator('[data-final-readback]').waitFor();await page.locator('[data-final-readback]').click();await page.waitForFunction(()=>document.querySelector('[data-final-notice]')?.textContent.includes('Current state:'));assert.equal((await current()).state,'Archived');assert.match(await page.locator('.fr-wom-note').textContent(),/Skipped/);await page.unroute('**'+route+'?handler=Finalize');cases.push('RC08 F1/F2 + AU18: applied lost response survives reload, cached readback shows official retained refresh outcome');
  await page.locator('[data-final-version]').first().click();await page.locator('.drawer').waitFor();assert.match(page.url(),/version=1/);await page.goBack();await page.locator('.drawer').waitFor({state:'detached'});await page.goForward();await page.locator('.drawer').waitFor();await page.locator('.drawer .dr-foot button').click();await page.locator('.drawer').waitFor({state:'detached'});
  await page.goto(fixture.origin+route+'?version=999');await page.locator('.drawer').waitFor();assert.match(await page.locator('.drawer').textContent(),/This version isn’t available/);await page.goto(fixture.origin+route+'?version=bad');await ready();await page.waitForFunction(()=>!location.search);assert.equal(await page.locator('.drawer').count(),0);cases.push('A2 / RC08 F3: direct, invalid, unavailable versions and Back/Forward drawer state');
  await page.locator('#reopen-btn').click();await page.locator('#fr-reason').waitFor();await page.locator('.modal [data-confirm-accept]').click();assert.match(await page.locator('.modal [role=alert]').textContent(),/Enter a reason/);await page.locator('#fr-reason').fill('Controlled late correction');assert.equal(await page.locator('#fr-reason').getAttribute('maxlength'),'2000');
  await page.reload();await ready();await page.locator('#reopen-btn').click();assert.equal(await page.locator('#fr-reason').inputValue(),'Controlled late correction');
  await page.route('**'+route+'?handler=Unfinalize',r=>r.fulfill({status:200,headers:{'Content-Type':'text/html','X-Bingo-Post-Navigation':'/Account/Login'},body:'<html>Sign in</html>'}));await page.locator('.modal [data-confirm-accept]').click();await page.getByRole('heading',{name:'Your changes were not saved'}).waitFor();assert.match(await page.locator('.kv').textContent(),/Controlled late correction/);await page.getByRole('button',{name:'Keep editing',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.modal').length===1);assert.equal(await page.locator('#fr-reason').inputValue(),'Controlled late correction');await page.unroute('**'+route+'?handler=Unfinalize');cases.push('C-CMP-2 / RC08 F2: reason survives reload and session loss, submitted data is explained first');
  await page.locator('.modal [data-confirm-accept]').click();await page.waitForFunction(()=>!document.querySelector('.modal')&&JSON.parse(document.querySelector('[data-final-review]').dataset.current).state==='AwaitingFinalReview');assert.notEqual((await current()).reviewCycleId,cycle);assert.equal((await current()).history[0].unfinalizeReason,'Controlled late correction');cases.push('B-Final-2 / RC08: in-place Reopen creates a new cycle and retains actor/reason history');
  await page.screenshot({path:path.join(output,'reopened-wide.png'),fullPage:true});await page.setViewportSize({width:390,height:900});await page.screenshot({path:path.join(output,'reopened-phone.png'),fullPage:true});assert.deepEqual(errors,[]);
  fs.writeFileSync(path.join(output,'results.json'),JSON.stringify({engine,cases},null,2));console.log('PASS '+cases.length+' Final Review browser scenarios ['+engine+']');
 }finally{await browser?.close();await fixture.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
