// U9: U9-Q1/Q2, WA-6, RC09 W3 (rate-limited and fetch-ready variants). Owned PostgreSQL/Kestrel only; shared harness in fixtures/admin-design-wom-harness.cjs.
const assert=require('node:assert/strict');
require('./fixtures/admin-design-wom-harness.cjs')('wom-fetch',async({scenario,cases})=>{
 await scenario('rate-limited',async({page,fixture,go})=>{await go('ur-current');assert.equal(await page.locator('#fetch-btn').isDisabled(),true);assert.match(await page.locator('[data-wom]').textContent(),/rate limit|retry/i);await page.goto(fixture.origin+'/Admin/Events/Finalize/'+fixture.events['ur-archived']);await page.locator('#reopen-btn').waitFor();assert.equal(await page.locator('#reopen-btn').isDisabled(),true);assert.match(await page.locator('#reopen-why').textContent(),/is still live.*publish its results/is);cases.push('U9-Q1: Live current event blocks Final Review Reopen with the ruled guidance');cases.push('U9-Q2 / WA-6: rate-limited next retry shown without a generic cooldown');});
 await scenario('fetch-ready',async({page,route,go,state,notice})=>{
  await go('ur-current');assert.equal(await page.locator('#fetch-btn').isEnabled(),true);const before=(await state()).integration.lastSuccessfulAt;
  await page.route('**'+route('ur-current')+'?handler=FetchCompetition',r=>r.fulfill({status:502,body:'response lost'}));await page.locator('#fetch-btn').click();await page.locator('[data-wom-readback]').waitFor();await page.locator('[data-wom-readback]').click();await page.waitForFunction(()=>document.querySelector('[data-wom-notice]')?.textContent.includes('Current stored connection:'));assert.equal((await state()).integration.lastSuccessfulAt,before);assert.match(await notice().textContent(),/couldn’t confirm whether new data was fetched.*Last successful fetch on record/is);await page.unroute('**'+route('ur-current')+'?handler=FetchCompetition');
  await page.route('**'+route('ur-current')+'?handler=FetchCompetition',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({succeeded:false,outcome:'skipped',skipReason:'WithinHour',message:'The last successful fetch was less than an hour ago.',retryAt:'2027-06-02T13:00:00Z'})}));await page.locator('#fetch-btn').click();await page.waitForFunction(()=>document.querySelector('[data-wom-notice]')?.textContent.includes('less than an hour'));assert.match(await notice().textContent(),/Next eligible time/);cases.push('RC09 W3 / U9-Q2: old timestamp never proves timed-out fetch finished; exact skipped reason and eligible time render in place');
 });
});
