namespace Bingo.BrowserTests;

public sealed class CatalogueUiTests
{
    [Fact]
    public void CatalogueUsesCardsAndAConnectedRouteEditorWithStandaloneFallback()
    {
        var root = FindRepositoryRoot();
        var page = File.ReadAllText(Path.Combine(root, "src", "Bingo.Web", "Pages", "Admin", "Catalogue", "Index.cshtml"));
        var model = File.ReadAllText(Path.Combine(root, "src", "Bingo.Web", "Pages", "Admin", "Catalogue", "Index.cshtml.cs"));
        var script = File.ReadAllText(Path.Combine(root, "src", "Bingo.Web", "wwwroot", "js", "catalogue-admin.js"));
        var styles = File.ReadAllText(Path.Combine(root, "src", "Bingo.Web", "wwwroot", "css", "site.css"));

        Assert.Equal("Kills per hour", Bingo.Web.Pages.Admin.Catalogue.IndexModel.RateLabel("Boss"));
        Assert.Equal("Kills per hour", Bingo.Web.Pages.Admin.Catalogue.IndexModel.RateLabel("Skilling boss"));
        Assert.Equal("Runs per hour", Bingo.Web.Pages.Admin.Catalogue.IndexModel.RateLabel("Minigame"));
        Assert.Equal("kill", Bingo.Web.Pages.Admin.Catalogue.IndexModel.RateUnit("Boss", 1m));
        Assert.Equal("kills", Bingo.Web.Pages.Admin.Catalogue.IndexModel.RateUnit("Skilling boss", 2m));
        Assert.Equal("run", Bingo.Web.Pages.Admin.Catalogue.IndexModel.RateUnit("Minigame", 1m));
        Assert.Equal("runs", Bingo.Web.Pages.Admin.Catalogue.IndexModel.RateUnit("Minigame", null));

        Assert.Contains("catalogue-record-card", page);
        Assert.Contains("data-catalogue-editor", page);
        Assert.Contains("data-catalogue-add", page);
        Assert.Contains("addBoss=true", page);
        Assert.Contains("AdminPageDescription", page);
        Assert.DoesNotContain("catalogue-page-heading", page);
        Assert.DoesNotContain("<p class=\"eyebrow\">Administration</p>", page);
        Assert.DoesNotContain("admin-button-primary", page);
        Assert.DoesNotContain("admin-dialog-page-kicker", page);
        Assert.Contains("@(Model.AddBoss ? \"catalogue-add-boss-dialog\" : null)", page);
        var addBoss = page[page.IndexOf("@if (Model.AddBoss)", StringComparison.Ordinal)..page.IndexOf("else if (selectedBoss is not null)", StringComparison.Ordinal)];
        Assert.Contains("<label asp-for=\"Boss.EfficientRate\" data-catalogue-rate-label>@IndexModel.RateLabel(Model.Boss.Category)</label>", addBoss);
        Assert.Contains("data-catalogue-rate-category", addBoss);
        Assert.Contains("@IndexModel.RateLabel(Model.Boss.Category)", addBoss);
        Assert.DoesNotContain("class=\"admin-button-secondary\" href=\"@pageUrl\">Cancel</a>", addBoss);
        Assert.Contains("class=\"admin-button-create\" type=\"submit\">", addBoss);
        Assert.DoesNotContain("admin-button-secondary", addBoss);
        Assert.Contains("<path d=\"M5 12h14\" />", addBoss);
        Assert.Contains("<path d=\"M12 5v14\" />", addBoss);
        Assert.Contains("<span>Add boss or activity</span>", addBoss);
        Assert.DoesNotContain("action-accent-outline", addBoss);
        Assert.Contains("<div class=\"catalogue-editor-wide catalogue-reference-heading\"><h3>Reference details</h3><p>Record the data source and use a direct OSRS Wiki image URL.</p></div>", addBoss);
        Assert.Contains("<input asp-for=\"Boss.DataSource\" class=\"form-control\" />", addBoss);
        Assert.Contains("<input asp-for=\"Boss.ImageUrl\" class=\"form-control\" type=\"url\" />", addBoss);
        Assert.DoesNotContain("boss-data-source-help", addBoss);
        Assert.DoesNotContain("boss-image-url-help", addBoss);
        Assert.DoesNotContain("aria-describedby", addBoss);
        Assert.Contains("@IndexModel.RateLabel(selectedBoss.Category)", page);
        Assert.DoesNotContain("Rolls per @IndexModel.RateUnit(selectedBoss.Category, null)", page);
        Assert.Contains("@IndexModel.RateUnit(boss.Category, boss.EfficientRate)/hour", page);
        Assert.DoesNotContain("completions/hour", page);
        Assert.DoesNotContain("Efficient completions per hour", page);
        var existingEditorStart = page.IndexOf("else if (selectedBoss is not null)", StringComparison.Ordinal);
        var existingEditor = page[existingEditorStart..page.IndexOf("@if (selectedDrops.Count == 0", existingEditorStart, StringComparison.Ordinal)];
        var existingFormStart = existingEditor.IndexOf("<form method=\"post\" asp-page-handler=\"UpdateBoss\"", StringComparison.Ordinal);
        var existingForm = existingEditor[existingFormStart..(existingEditor.IndexOf("</form>", existingFormStart, StringComparison.Ordinal) + "</form>".Length)];
        Assert.DoesNotContain("admin-dialog-page-kicker", existingEditor);
        Assert.DoesNotContain("eyebrow", existingEditor);
        Assert.Contains("<h2 id=\"catalogue-editor-title\">@(Model.AddBoss ? \"Add boss or activity\" : selectedBoss?.Name)</h2>", page);
        Assert.Contains("class=\"admin-button-secondary\" type=\"submit\">Save activity</button>", existingForm);
        Assert.DoesNotContain("action-accent-outline", existingForm);
        Assert.DoesNotContain("admin-button-create", existingForm);
        Assert.Contains("asp-page-handler=\"UpdateBoss\"", existingForm);
        Assert.Contains("name=\"recordId\" value=\"@selectedBoss.Id\"", existingForm);
        Assert.Contains("name=\"expectedVersion\" value=\"@selectedBoss.Version\"", existingForm);
        var addSectionStart = existingEditor.IndexOf("<section class=\"catalogue-add-drop-section\"", StringComparison.Ordinal);
        var addSection = existingEditor[addSectionStart..(existingEditor.IndexOf("</section>", addSectionStart, StringComparison.Ordinal) + "</section>".Length)];
        var addDropStart = addSection.IndexOf("<form method=\"post\" asp-page-handler=\"BossDrop\"", StringComparison.Ordinal);
        var addDrop = addSection[addDropStart..(addSection.IndexOf("</form>", addDropStart, StringComparison.Ordinal) + "</form>".Length)];
        var dropsStart = existingEditor.IndexOf("<section class=\"catalogue-drop-section\"", StringComparison.Ordinal);
        var drops = existingEditor[dropsStart..];
        Assert.Contains("<h3 id=\"catalogue-add-drop-heading\">Add drop</h3>", addSection);
        Assert.Contains("<p>Add a drop to this activity.</p>", addSection);
        Assert.Contains("<h3 id=\"catalogue-drops-heading\">Drops</h3>", drops);
        Assert.Contains("<p>Review and manage the configured drops and their EHB values.</p>", drops);
        Assert.Contains("class=\"catalogue-section-count\">@selectedDrops.Count configured</span>", drops);
        Assert.DoesNotContain("Expected EHB = 1 ÷", page);
        Assert.DoesNotContain("Enter the chance that one participant receives the item.", page);
        Assert.Contains("class=\"admin-button-create\" type=\"submit\"><svg", addDrop);
        Assert.Contains("<path d=\"M5 12h14\" />", addDrop);
        Assert.Contains("<path d=\"M12 5v14\" />", addDrop);
        Assert.Contains("<span>Add drop</span>", addDrop);
        Assert.DoesNotContain("action-accent-outline", addDrop);
        Assert.Contains("asp-page-handler=\"BossDrop\"", addDrop);
        Assert.Contains("name=\"BossId\" value=\"@selectedBoss.Id\"", addDrop);
        Assert.Contains("name=\"BossDrop.BossActivityId\" value=\"@selectedBoss.Id\"", addDrop);
        Assert.Contains("Rolls per @IndexModel.RateUnit(selectedBoss.Category, 1m)", addSection);
        Assert.Contains("data-catalogue-drop-row", page);
        Assert.Contains("data-catalogue-drop-initial-expanded=\"@(Model.DropId == drop.Id ? \"true\" : \"false\")\"", page);
        Assert.Contains("class=\"catalogue-drop-summary\"", page);
        Assert.Contains("<small>@drop.DisplayRate · @(drop.DefaultEhb?.ToString(\"0.####\") ?? \"Not available\") EHB</small>", page);
        Assert.DoesNotContain("<small>• ", page);
        Assert.DoesNotContain("Rolls per @IndexModel.RateUnit(selectedBoss.Category, null)", page);
        Assert.Equal(2, page.Split("Rolls per @IndexModel.RateUnit(selectedBoss.Category, 1m)", StringSplitOptions.None).Length - 1);
        Assert.Contains("var dropMissingProbability = drop.Probability is null or <= 0;", page);
        Assert.Contains("<span class=\"catalogue-drop-status-actions\">@if (dropMissingProbability) { <span class=\"admin-status-pill is-yellow\">Missing probability</span> } <span class=\"admin-status-pill @(drop.Active ? \"is-green\" : \"is-muted\")\">@(drop.Active ? \"Active\" : \"Inactive\")</span></span>", page);
        Assert.Contains("class=\"admin-status-pill @(drop.Active ? \"is-green\" : \"is-muted\")\"", page);
        Assert.Contains("data-catalogue-drop-toggle", page);
        Assert.Contains("aria-label=\"Edit @drop.ItemName\"", page);
        Assert.DoesNotContain("class=\"catalogue-status", page);
        Assert.DoesNotContain("class=\"catalogue-warning\"", page);
        Assert.Contains("data-catalogue-drop-editor", page);
        Assert.Contains("id=\"catalogue-drop-form-@drop.Id\" method=\"post\" asp-page-handler=\"UpdateDrop\"", page);
        Assert.Contains("name=\"useExistingItem\" value=\"false\" data-use-existing-item", page);
        Assert.Contains("name=\"originalDisplayRate\" value=\"@drop.DisplayRate\"", page);
        Assert.Contains("name=\"originalNumericProbability\"", page);
        Assert.Contains("<div class=\"catalogue-drop-actions\">\n                                            <button class=\"admin-button-secondary\" type=\"submit\" form=\"catalogue-drop-form-@drop.Id\">Save drop</button>", page);
        Assert.DoesNotContain("catalogue-drop-card-actions", page);
        Assert.DoesNotContain("catalogue-drop-form-actions", page);
        Assert.DoesNotContain("catalogue-drop-lifecycle-actions", page);
        Assert.Contains("data-catalogue-duplicate-confirm", page);
        Assert.Contains("class=\"admin-button-secondary\" data-catalogue-duplicate-confirm>Use existing item</button>", page);
        Assert.Contains("class=\"admin-destructive-confirmation catalogue-confirmation-box\"", page);
        Assert.Contains("<summary class=\"admin-button-secondary action-danger-outline\">Deactivate drop</summary>", page);
        Assert.Contains("<button class=\"admin-button-secondary action-danger-outline\" type=\"submit\">Deactivate drop</button>", page);
        Assert.Contains("<strong id=\"deactivate-drop-@drop.Id\">Deactivate @drop.ItemName?</strong><span>The drop remains in the catalogue and can be reactivated later.</span>", page);
        Assert.Contains("<strong id=\"delete-drop-@drop.Id\">Delete @drop.ItemName permanently?</strong><span>Only an unused catalogue record can be deleted.</span>", page);
        Assert.Contains("<summary class=\"admin-button-secondary action-danger-outline\">Deactivate activity</summary>", page);
        Assert.Contains("<button class=\"admin-button-secondary action-danger-outline\" type=\"submit\">Deactivate activity</button>", page);
        Assert.Contains("<strong id=\"deactivate-boss-@selectedBoss.Id\">Deactivate @selectedBoss.Name?</strong><span>The activity remains in the catalogue and can be reactivated later.</span>", page);
        Assert.Contains("<strong id=\"delete-boss-@selectedBoss.Id\">Delete @selectedBoss.Name permanently?</strong><span>Only an unused catalogue record can be deleted.</span>", page);
        Assert.DoesNotContain("</strong><br />", page);
        Assert.DoesNotContain("<summary class=\"action-danger-outline\">", page);
        Assert.DoesNotContain("<button class=\"action-danger-outline\" type=\"submit\">", page);
        Assert.Contains("Reactivate drop", page);
        var directoryStart = page.IndexOf("<div class=\"admin-events-directory-controls", StringComparison.Ordinal);
        var directory = page[directoryStart..page.IndexOf("</div>\n        <aside class=\"information-callout\"", directoryStart, StringComparison.Ordinal)];
        Assert.Contains("class=\"admin-events-directory-controls catalogue-directory-controls\"", directory);
        Assert.Contains("class=\"admin-events-toolbar\"", directory);
        Assert.Contains("class=\"admin-search-field admin-events-search\"", directory);
        Assert.Contains("class=\"admin-search-field-input form-control\"", directory);
        Assert.Contains("<button class=\"admin-search-clear\" type=\"button\" data-admin-search-clear aria-label=\"Clear catalogue search\" hidden>", directory);
        Assert.Contains("<path d=\"m6 6 12 12\" />", directory);
        Assert.Contains("<path d=\"m18 6-12 12\" />", directory);
        Assert.Contains("class=\"admin-events-state-filter admin-field\"", directory);
        Assert.Contains("class=\"admin-filter-select form-select\"", directory);
        Assert.Contains("data-catalogue-category-filter", directory);
        foreach (var option in new[] { "All", "Boss", "Skilling boss", "Minigame", "Inactive" }) Assert.Contains($">{option}</option>", directory);
        Assert.Equal(5, directory.Split("<option ", StringSplitOptions.None).Length - 1);
        Assert.Contains("class=\"admin-button-create\"", directory);
        Assert.Contains("<path d=\"M5 12h14\" />", directory);
        Assert.Contains("<span>Add boss or activity</span>", directory);
        Assert.DoesNotContain("catalogue-filters", directory);
        Assert.DoesNotContain("data-catalogue-filter", directory);
        Assert.DoesNotContain("action-accent-outline", directory);
        var informationCalloutStart = page.IndexOf("<aside class=\"information-callout\" role=\"note\">", StringComparison.Ordinal);
        var informationCallout = page[informationCalloutStart..(page.IndexOf("</aside>", informationCalloutStart, StringComparison.Ordinal) + "</aside>".Length)];
        Assert.DoesNotContain("catalogue-directory-information-row", page);
        Assert.Contains("<div class=\"information-callout-heading\"><svg class=\"information-callout-icon\" aria-hidden=\"true\"", informationCallout);
        Assert.Contains("<strong>Team content</strong></div><span>", informationCallout);
        Assert.Contains("When adding a drop for team content, enter the chance of receiving it in your own name at the team size used for the EHB rate. For example, in a five-player Nex team, your personal chance of receiving a Nihil horn is 1/1,290 per kill.</span></aside>", informationCallout);
        Assert.DoesNotContain("boss-result-count", page);
        Assert.DoesNotContain("catalogue-result-count", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page > .information-callout { margin: 0.75rem 0 0.65rem; background: var(--admin-surface); }", styles);
        Assert.Contains("catalogue-card-status admin-status-pill @(boss.Active ? \"is-green\" : \"is-muted\")", page);
        Assert.Contains("admin-status-pill is-yellow", page);
        Assert.Contains("<strong>@boss.Name</strong><small class=\"catalogue-card-meta\">", page);
        Assert.DoesNotContain("<strong>@boss.Name</strong><span class=\"catalogue-card-meta\">", page);
        Assert.Contains("data-update-targets=\"@partialTargets\"", page);
        Assert.Contains("Concat(bossDrops.Select(x => x.ItemName))", page);
        Assert.Contains("bossDrops.Count(x => x.Active &&", page);
        Assert.DoesNotContain("<details class=\"panel catalogue-record", page);
        Assert.DoesNotContain("add-drop-dialog", page);
        Assert.DoesNotContain("data-confirm=", page);
        Assert.Contains("catalogue-confirmation-box", page);
        Assert.Contains("data-catalogue-confirmation-cancel", page);
        Assert.Contains("[BindProperty(SupportsGet = true)] public bool Overlay", model);
        Assert.Contains("[BindProperty(SupportsGet = true)] public Guid? DropId", model);
        Assert.Contains("overlay = IsOverlay ? \"1\" : null", model);
        Assert.Contains("dropId = DropId", model);
        Assert.Contains("addBoss = AddBoss ? \"true\" : null", model);

        Assert.Contains("grid-template-columns: repeat(3, minmax(0, 1fr))", styles);
        Assert.Contains("@media (max-width: 1100px)", styles);
        Assert.Contains("@media (max-width: 900px)", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .admin-events-directory-controls", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-editor-heading h2 { margin: 0; color: var(--admin-text); font-family: inherit; font-size: 1.0625rem; font-weight: 600; line-height: 1.25; }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-editor-dialog-page:not(.catalogue-add-boss-dialog) { gap: 1.25rem; }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-editor-dialog-page:not(.catalogue-add-boss-dialog) > .catalogue-editor-heading { margin-bottom: 0; }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-editor-dialog-page:not(.catalogue-add-boss-dialog) .catalogue-editor-heading #catalogue-editor-description { margin: 0.35rem 0 0; color: var(--admin-muted); font-family: inherit; font-size: 0.6875rem; font-weight: 400; line-height: 1.4; }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-add-boss-dialog.catalogue-editor-dialog-page { gap: 1.25rem; padding: 1.25rem; background: var(--admin-surface); border: 0; border-radius: 0.75rem; }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-add-boss-dialog.catalogue-editor-dialog-page > .catalogue-editor-heading { margin-bottom: 0; }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-add-boss-dialog.catalogue-editor-dialog-page .catalogue-editor-heading #catalogue-editor-description { margin: 0.35rem 0 0; color: var(--admin-muted); font-size: 0.6875rem; line-height: 1.4; }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-add-boss-dialog .catalogue-editor-form { padding: 1.25rem; background: var(--admin-surface-soft); border: 0; border-radius: 0.75rem; }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-add-boss-dialog .catalogue-reference-heading { display: block; }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-add-boss-dialog .catalogue-reference-heading h3 { margin: 0; color: var(--admin-text); font-size: 0.8125rem; font-weight: 600; line-height: 1.3; }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-add-boss-dialog .catalogue-reference-heading p { margin: 0.25rem 0 0; color: var(--admin-muted); font-size: 0.6875rem; font-weight: 400; line-height: 1.4; }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-editor-body { display: grid; gap: 1.25rem; }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-editor-body > .catalogue-editor-form { padding: 1.25rem; background: var(--admin-surface-soft); border: 0; border-radius: 0.75rem; }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-editor-body > .catalogue-add-drop-section,\n.admin-shell-body .admin-catalogue-page .catalogue-editor-body > .catalogue-drop-section { display: grid; gap: 1.25rem; padding: 1.25rem; background: var(--admin-surface-soft); border: 0; border-radius: 0.75rem; }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-editor-body > .catalogue-add-drop-section > .catalogue-section-heading h3,\n.admin-shell-body .admin-catalogue-page .catalogue-editor-body > .catalogue-drop-section > .catalogue-section-heading h3 { margin: 0; color: var(--admin-text); font-family: inherit; font-size: 0.8125rem; font-weight: 600; line-height: 1.3; }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-editor-body > .catalogue-add-drop-section > .catalogue-section-heading p,\n.admin-shell-body .admin-catalogue-page .catalogue-editor-body > .catalogue-drop-section > .catalogue-section-heading p { margin: 0.25rem 0 0; color: var(--admin-muted); font-family: inherit; font-size: 0.6875rem; font-weight: 400; line-height: 1.4; }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-editor-body > .catalogue-drop-section > .catalogue-section-heading .catalogue-section-count { color: var(--admin-muted); font-family: inherit; font-size: 0.625rem; font-weight: 400; line-height: 1.4; }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-editor-body > .catalogue-add-drop-section > .catalogue-add-drop-form,\n.admin-shell-body .admin-catalogue-page .catalogue-editor-body > .catalogue-drop-section > .catalogue-add-drop-form { padding: 0; background: transparent; border: 0; border-radius: 0; }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-drop-editor .form-control,\n.admin-shell-body .admin-catalogue-page .catalogue-drop-editor .form-select { min-height: 2.25rem; padding: 0.4rem 0.6rem; color: var(--admin-text); background: var(--admin-surface-raised); border: 1px solid var(--admin-border-strong); border-radius: 0.5rem; font-family: inherit; font-size: 0.75rem; font-weight: 400; line-height: 1.25; }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-drop-editor .form-control:focus,", styles);
        Assert.Contains("border-color: var(--admin-focus-accent); box-shadow: 0 0 0 0.15rem color-mix(in srgb, var(--admin-focus-accent) 20%, transparent); outline: 0;", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-drop-editor .admin-field > small { margin: 0; color: var(--admin-muted); font-family: inherit; font-size: 0.625rem; font-weight: 400; line-height: 1.4; }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-ehb-result output { display: flex; min-height: 2.25rem; align-items: center; padding: 0.4rem 0.6rem; color: var(--admin-text); background: var(--admin-surface-raised); border: 1px solid var(--admin-border-strong); border-radius: 0.5rem; font-family: inherit; font-size: 0.75rem; font-weight: 400; line-height: 1.25; }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-drop-editor { margin-top: 0.75rem; padding-top: 1rem; }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-drop-actions { display: flex; flex-wrap: wrap; justify-content: flex-end; gap: 0.5rem; align-items: center; margin-top: 1rem; }", styles);
        Assert.DoesNotContain("catalogue-drop-lifecycle-actions", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-editor-footer { display: flex; justify-content: flex-end; gap: 0.5rem; padding-top: 0.75rem; }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-drop-list { display: grid; grid-template-columns: 1fr; gap: 0.75rem; }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-drop-card { display: block; min-width: 0; min-height: 4rem; padding: 0.75rem 1rem; background: var(--admin-surface); border: 0; border-radius: 0.75rem; }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-drop-summary { display: grid; grid-template-columns: 2.5rem minmax(0, 1fr) auto auto; gap: 0.75rem; align-items: center; min-height: 2.5rem; }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-drop-summary-copy strong { overflow: hidden; color: var(--admin-text); font-family: inherit; font-size: 0.8125rem; font-weight: 600; line-height: 1.3; text-overflow: ellipsis; white-space: nowrap; }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-drop-summary-copy small { display: block; overflow: hidden; color: var(--admin-muted); font-family: inherit; font-size: 0.625rem; font-weight: 400; line-height: 1.4; text-overflow: ellipsis; white-space: nowrap; }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-drop-status-actions { display: flex; flex-wrap: wrap; align-items: center; justify-content: flex-end; gap: 0.5rem; }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-drop-edit-toggle { display: inline-flex; width: 2rem; height: 2rem;", styles);
        Assert.DoesNotContain(".admin-shell-body .admin-catalogue-page .catalogue-drop-editor { margin-top: 0.75rem; padding-top: 1rem; border-top:", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-drop-edit-form { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 0.75rem; align-items: start; }", styles);
        Assert.DoesNotContain(".admin-shell-body .admin-catalogue-page .catalogue-drop-lifecycle-actions { margin-top: 0.75rem; padding-top: 0.75rem; border-top:", styles);
        Assert.DoesNotContain(".admin-shell-body .admin-catalogue-page .catalogue-editor-footer { display: flex; justify-content: flex-end; gap: 0.5rem; padding-top: 0.75rem; border-top:", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-confirmation-box[open] > .event-confirmation-box { position: fixed; z-index: 30; top: 50%; left: 50%; width: min(24rem, calc(100vw - 2rem)); margin: 0; padding: 1rem; background: var(--admin-surface); border: 1px solid var(--admin-border-strong); border-radius: 0.75rem; transform: translate(-50%, -50%); box-shadow: 0 1rem 3rem rgb(0 0 0 / 35%); }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-confirmation-box .event-confirmation-box p { margin: 0; }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-confirmation-box .event-confirmation-box p > strong { display: block; margin: 0; color: var(--admin-text); font-family: inherit; font-size: 0.8125rem; font-weight: 600; line-height: 1.3; }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-confirmation-box .event-confirmation-box p > span { display: block; margin: 0.25rem 0 0; color: var(--admin-muted); font-family: inherit; font-size: 0.6875rem; font-weight: 400; line-height: 1.4; }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-confirmation-box .event-confirmation-box form { display: grid; gap: 0.75rem; }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-drop-summary { grid-template-columns: 2.5rem minmax(0, 1fr) auto; }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-drop-summary > .catalogue-drop-status-actions { grid-column: 2; grid-row: 2; justify-self: start; }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-drop-edit-form { grid-template-columns: 1fr; }", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-record-card {", styles);
        Assert.Contains("border: 0", styles[styles.IndexOf(".admin-shell-body .admin-catalogue-page .catalogue-record-card {", StringComparison.Ordinal)..]);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-card-content > strong { display: block; color: var(--admin-text); font-size: 0.8125rem; font-weight: 600; line-height: 1.3;", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .catalogue-card-content > .catalogue-card-meta { display: block; margin-top: 0.15rem; color: var(--admin-muted); font-family: inherit; font-size: 0.625rem; font-weight: 400; line-height: 1.5;", styles);
        Assert.Contains("padding: 1.25rem 0 3rem;", styles[styles.IndexOf(".admin-shell-body .admin-catalogue-page {", StringComparison.Ordinal)..]);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .admin-search-field-input:focus,\n.admin-shell-body .admin-catalogue-page .admin-search-field-input:focus-visible { color: var(--admin-text); background: var(--admin-search); border-color: var(--admin-focus-accent); box-shadow: 0 0 0 0.15rem color-mix(in srgb, var(--admin-focus-accent) 20%, transparent); outline: 0; }", styles);
        Assert.Contains(".admin-shell-body .admin-search-field-input {\n  width: 100%;\n  min-height: 2.25rem;\n  padding: 0.4rem 2.25rem 0.4rem 2.25rem;\n  color: var(--admin-text);\n  background: var(--admin-search);\n  border: 1px solid var(--admin-border);\n  border-radius: 0.5rem;\n  font-size: 0.75rem;\n  line-height: 1.25;\n  transition: none;\n}", styles);
        Assert.Contains(".admin-shell-body .admin-events-page .admin-search-field-input:focus,\n.admin-shell-body .admin-events-page .admin-search-field-input:focus-visible,\n.admin-shell-body .event-participants-page .admin-search-field-input:focus,\n.admin-shell-body .event-participants-page .admin-search-field-input:focus-visible { color: var(--admin-text); background: var(--admin-search); border-color: var(--admin-focus-accent); box-shadow: 0 0 0 0.15rem color-mix(in srgb, var(--admin-focus-accent) 20%, transparent); outline: 0; }", styles);
        Assert.Contains(".admin-shell-body .admin-filter-select:hover { border-color: var(--admin-border); }", styles);
        Assert.DoesNotContain(".admin-shell-body .admin-catalogue-page .admin-filter-select:hover", styles);
        Assert.Contains(".admin-shell-body .admin-catalogue-page .admin-events-state-filter > svg { width: 1rem; height: 1rem; color: var(--admin-muted); }", styles);
        var paletteStart = styles.IndexOf(".admin-shell-body .admin-header,", StringComparison.Ordinal);
        var paletteEnd = styles.IndexOf("}\n.admin-shell-body { --admin-content-gutter", paletteStart, StringComparison.Ordinal);
        var palette = styles[paletteStart..paletteEnd];
        Assert.Contains(".admin-shell-body .admin-catalogue-page,", palette);
        Assert.Contains("--admin-text: #eaeae5;", palette);
        Assert.Contains("--admin-text-soft: #c2c2be;", palette);
        Assert.Contains("--admin-muted: #969692;", palette);
        var catalogueStyles = styles[styles.IndexOf("/* Catalogue directory", StringComparison.Ordinal)..];
        foreach (var selector in new[] { ".admin-events-state-chevron {", ".admin-search-field-input {" })
        {
            var start = catalogueStyles.IndexOf(selector, StringComparison.Ordinal);
            if (start < 0) continue;
            var end = catalogueStyles.IndexOf('}', start);
            var rule = catalogueStyles[start..end];
            Assert.DoesNotContain(" color:", rule);
            Assert.DoesNotContain("font-", rule);
        }
        Assert.DoesNotContain(".admin-shell-body .admin-catalogue-page .admin-button-create", catalogueStyles);

        Assert.Contains("loadDirectWorkspace", script);
        Assert.Contains("const cataloguePage = parsed.querySelector(\"[data-catalogue-page]\")", script);
        Assert.Contains("main.hidden = true", script);
        Assert.Contains("document.body.contains(dialog)", script);
        Assert.Contains("dialog.showModal()", script);
        Assert.Contains("dialog.addEventListener(\"keydown\"", script);
        Assert.Contains("history.back()", script);
        Assert.Contains("window.location.replace", script);
        Assert.Contains("bingo:content-updated", script);
        Assert.Contains("selectors.includes(\".catalogue-editor-component\")", script);
        Assert.Contains("catalogueCloseReady", script);
        Assert.Contains("bindDropEditors", script);
        Assert.Contains("data-catalogue-drop-toggle", script);
        Assert.Contains("rows.forEach(other => setExpanded(other, false))", script);
        Assert.Contains("dropId", script);
        Assert.DoesNotContain("form[data-confirm]", script);
        Assert.Contains("if (directRoute && main instanceof HTMLElement) main.hidden = false", script);
        Assert.Contains("data-catalogue-category-filter", script);
        Assert.Contains("const clear = root.querySelector(\"[data-admin-search-clear]\")", script);
        Assert.Contains("clear.hidden = search.value.trim().length === 0", script);
        Assert.Contains("clear?.addEventListener(\"click\", () => { search.value = \"\"; applyFilters(); search.focus(); })", script);
        Assert.DoesNotContain("data-catalogue-filter", script);
        Assert.Contains("data-catalogue-rate-category", script);
        Assert.Contains("data-catalogue-rate-label", script);
        Assert.Contains("category.value === \"Minigame\" ? \"Runs per hour\" : \"Kills per hour\"", script);
    }

    private static string FindRepositoryRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "Bingo.slnx"))) directory = directory.Parent;
        return directory?.FullName ?? throw new InvalidOperationException("Repository root was not found.");
    }
}
