const assert=require('node:assert/strict'),path=require('node:path');const {chromium,webkit}=require('playwright');const {startFixture,login}=require('../../scripts/lib/admin-parity-fixture.cjs');
(async()=>{const engine=process.env.PLAYWRIGHT_BROWSER||'chromium',fixture=await startFixture(process.cwd(),path.join(process.cwd(),'artifacts/signup-settings-parity-'+engine));let browser;
try{browser=await(engine==='webkit'?webkit:chromium).launch({headless:true});const context=await browser.newContext(),page=await login(context,fixture),route='/Admin/Events/SignupSetup/'+fixture.events['autumn-bingo-2027'],errors=[];page.on('pageerror',e=>errors.push(e.message));let cases=0;
for(const language of ['en','da']){await page.goto(fixture.origin+route);await page.locator('#cap-save [data-save-label]').waitFor();if(language==='da'){await page.locator('[name=culture][value=da]').click();await page.waitForFunction(()=>document.documentElement.lang==='da');await page.locator('#cap-save [data-save-label]').waitFor();}
const text=await page.locator('[data-signup-text]').getAttribute('data-labels').then(JSON.parse),t=(key,...args)=>(text[key]||key).replace(/\{(\d+)\}/g,(_,i)=>args[+i]);
async function load(cap,confirmed,waiting,stored=false,editable=true){await page.evaluate(async({cap,confirmed,waiting,stored,editable})=>{const root=document.querySelector('[data-signup-setup]'),s=JSON.parse(root.dataset.current);Object.assign(s,{confirmed,waiting,editable});Object.assign(s.settings,{participantCap:cap,requireSignupCode:stored,hasSignupCode:stored});root.dataset.current=JSON.stringify(s);document.querySelector('#cap-input').value=cap??'';document.querySelector('#code-on').checked=stored;document.querySelector('#code-new').value='';const m=await import(document.querySelector('script[data-admin-page-script]').src);await m.init(document.querySelector('[data-page-region]'));},{cap,confirmed,waiting,stored,editable});}
for(const [cap,confirmed,waiting,next,key,args] of [
[20,20,5,22,'Saving confirms the first {0} players on the waiting list, in waiting-list order. They’re told their place is confirmed.',[2]],
[20,20,2,21,'Saving confirms the first {0} player on the waiting list, in waiting-list order. They’re told their place is confirmed.',[1]],
[20,10,0,25,'{0} places will be open.',[15]],
[null,4,0,4,'The event will be full.',[]],
[20,10,0,10,'No one loses their place. The event will be full, so new signups join the waiting list.',[]],
[20,10,0,15,'No one loses their place. Once {0} players are confirmed, new signups join the waiting list.',[15]]]){await load(cap,confirmed,waiting);await page.locator('#cap-input').fill(String(next));let expected=t(key,...args);if(waiting>next-confirmed)expected+=' '+t(waiting-next+confirmed===1?'{0} player stays on the waiting list.':'{0} players stay on the waiting list.',waiting-next+confirmed);assert.equal(await page.locator('#cap-note span').innerText(),expected);assert.equal(await page.locator('#cap-note').isVisible(),true);assert.equal(await page.locator('#cap-note [data-icon=info]').count(),1);cases++;}
await load(20,10,0);assert.equal(await page.locator('#code-on-sub').innerText(),t('Anyone with the signup link can sign up.'));await page.locator('#code-on').check();assert.equal(await page.locator('#code-on-sub').innerText(),t('Players must enter the code before they can sign up.'));assert.equal(await page.locator('label[for=code-new]').innerText(),t('Code'));assert.equal(await page.locator('#signup-code-help').innerText(),t('Players type this exactly as you enter it. Up to 100 characters.'));assert.equal(await page.locator('#code-save').innerText(),t('Save signup code'));await page.locator('#code-new').fill('x'.repeat(85));assert.equal(await page.locator('[data-code-count]').isVisible(),false);await page.locator('#code-new').fill('x'.repeat(86));assert.equal(await page.locator('[data-code-count]').isVisible(),true);await page.locator('#code-new').fill('x'.repeat(101));assert.match(await page.locator('[data-code-count]').getAttribute('class'),/is-over/);await page.locator('#code-save').click();assert.equal(await page.locator('#signup-code-error [data-icon=error]').count(),1);cases++;
await load(20,10,0,true);assert.equal(await page.locator('label[for=code-new]').innerText(),t('New code'));assert.equal(await page.locator('#signup-code-help').innerText(),t('Leave it empty to keep the current code.'));assert.equal(await page.locator('[data-code-stored] [data-icon=lock]').count(),1);await page.locator('#code-new').fill('Replacement');assert.equal(await page.locator('[data-code-note] span').innerText(),t('Saving replaces the current code. Players need the new one from then on.'));await page.locator('#code-on').uncheck();assert.equal(await page.locator('[data-code-note] span').innerText(),t('Saving turns protection off and deletes the stored code. Anyone with the signup link can then sign up. To turn it on again later, you’ll set a new code.'));assert.equal(await page.locator('[data-code-note] [data-icon=info]').count(),1);cases++;
await load(20,10,0,true,false);assert.equal(await page.locator('[data-cap-readonly]').innerText(),t('{0} players',20));assert.equal(await page.locator('[data-card-bar=cap]').isVisible(),false);assert.equal(await page.locator('[data-code-editable]').isVisible(),false);await load(null,0,0,false,false);assert.match(await page.locator('[data-cap-readonly]').getAttribute('class'),/is-empty/);cases++;
}
assert.deepEqual(errors,[]);console.log('PASS '+cases+' English/Danish Settings reference cases: capacity consequences, code deletion/replacement, dynamic wording, counters, icons, validation and read-only values.');
}finally{await browser?.close();await fixture.close();}})().catch(e=>{console.error(e);process.exitCode=1});
