using System.ComponentModel.DataAnnotations;
using Bingo.Application.Access;
using Bingo.Application.Auditing;
using Bingo.Application.Boards;
using Bingo.Domain.Boards;
using Bingo.Infrastructure.Persistence;
using Bingo.Web.Security;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
namespace Bingo.Web.Pages.Admin.Tiles;

[Authorize(Policy = AuthorizationPolicies.Admin)]
public sealed class RequirementsModel(ApplicationDbContext dbContext, IAuditWriter auditWriter) : PageModel
{
    public string TileName { get; private set; } = string.Empty; public IReadOnlyList<BossRow> Bosses { get; private set; } = []; public IReadOnlyList<DropRow> Drops { get; private set; } = []; public IReadOnlyList<RequirementRow> Existing { get; private set; } = []; [BindProperty] public RequirementInput Input { get; set; } = new();
    public async Task<IActionResult> OnGetAsync(Guid id, CancellationToken ct) => await Load(id, ct) ? Page() : NotFound();
    public async Task<IActionResult> OnPostAsync(Guid id, CancellationToken ct) { if (!await Load(id, ct)) return NotFound(); if (!Input.Manual && Input.DropIds.Count == 0) ModelState.AddModelError(string.Empty, "Select at least one eligible drop, or mark this as manual."); if (!ModelState.IsValid) return Page(); var position = (await dbContext.TileTemplateRequirements.Where(x => x.TileTemplateId == id).MaxAsync(x => (int?)x.Position, ct) ?? 0) + 1; var req = new TileTemplateRequirement(Guid.NewGuid(), id, position, Input.Target, Input.DuplicatesAllowed, Input.AllowHigherWeightings, Input.Description.Trim(), Input.Manual); dbContext.TileTemplateRequirements.Add(req); foreach (var boss in Input.BossIds.Distinct()) dbContext.TemplateRequirementBosses.Add(new TemplateRequirementBoss(Guid.NewGuid(), req.Id, boss)); foreach (var drop in Input.DropIds.Distinct()) dbContext.TemplateRequirementDrops.Add(new TemplateRequirementDrop(Guid.NewGuid(), req.Id, drop, Input.DuplicatesAllowed ? null : 1)); await dbContext.SaveChangesAsync(ct); await Audit("tile.requirement_created", id, req.Description, ct); return RedirectToPage(new { id }); }
    public async Task<IActionResult> OnPostMetadataAsync(Guid id, string name, string description, ObjectiveType objectiveType, string evidenceInstructions, decimal? manualEhb, CancellationToken ct) { if (string.IsNullOrWhiteSpace(name) || string.IsNullOrWhiteSpace(description) || string.IsNullOrWhiteSpace(evidenceInstructions) || manualEhb < 0) return BadRequest(); var tile = await dbContext.TileTemplates.SingleOrDefaultAsync(x => x.Id == id, ct); if (tile is null) return NotFound(); tile.Update(name.Trim(), description.Trim(), objectiveType, evidenceInstructions.Trim(), manualEhb); await dbContext.SaveChangesAsync(ct); await Audit("tile.updated", id, tile.Name, ct); return RedirectToPage(new { id }); }
    public async Task<IActionResult> OnPostRemoveAsync(Guid id, Guid requirementId, CancellationToken ct) { var requirement = await dbContext.TileTemplateRequirements.SingleOrDefaultAsync(x => x.Id == requirementId && x.TileTemplateId == id, ct); if (requirement is null) return NotFound(); var bosses = await dbContext.TemplateRequirementBosses.Where(x => x.RequirementId == requirementId).ToListAsync(ct); var drops = await dbContext.TemplateRequirementDrops.Where(x => x.RequirementId == requirementId).ToListAsync(ct); dbContext.TemplateRequirementBosses.RemoveRange(bosses); dbContext.TemplateRequirementDrops.RemoveRange(drops); dbContext.TileTemplateRequirements.Remove(requirement); await dbContext.SaveChangesAsync(ct); await Audit("tile.requirement_removed", id, requirement.Description, ct); return RedirectToPage(new { id }); }
    private async Task<bool> Load(Guid id, CancellationToken ct) { var tile = await dbContext.TileTemplates.AsNoTracking().SingleOrDefaultAsync(x => x.Id == id, ct); if (tile is null) return false; TileName = tile.Name; Bosses = await dbContext.BossActivities.AsNoTracking().Where(x => x.Active).OrderBy(x => x.Name).Select(x => new BossRow(x.Id, x.Name)).ToListAsync(ct); Drops = await (from d in dbContext.SourceDrops.AsNoTracking() join b in dbContext.BossActivities on d.BossActivityId equals b.Id join i in dbContext.CatalogueItems on d.ItemId equals i.Id where d.Active && b.Active && i.Active orderby b.Name, i.Name select new DropRow(d.Id, b.Name, i.Name, d.DisplayRate)).ToListAsync(ct); var reqs = await dbContext.TileTemplateRequirements.AsNoTracking().Where(x => x.TileTemplateId == id).OrderBy(x => x.Position).ToListAsync(ct); var rows = new List<RequirementRow>(); foreach (var r in reqs) { decimal? ehb = null; if (!r.ManualObjective) { var rates = await (from link in dbContext.TemplateRequirementDrops where link.RequirementId == r.Id join d in dbContext.SourceDrops on link.SourceDropId equals d.Id join b in dbContext.BossActivities on d.BossActivityId equals b.Id select new EligibleDropRate(b.EfficientCompletionsPerHour, d.NumericProbability, d.ItemId)).ToListAsync(ct); ehb = EhbCalculator.CalculateDropRequirement(r.TargetContribution, rates, r.DuplicatesAllowed); } rows.Add(new RequirementRow(r.Id, r.Position, r.Description, r.TargetContribution, r.ManualObjective, r.DuplicatesAllowed, r.AllowHigherWeightings, ehb)); } Existing = rows; Metadata = new(tile.Name, tile.Description, tile.ObjectiveType, tile.EvidenceInstructions, tile.ManualEhbOverride); return true; }
    public TileMetadata Metadata { get; private set; } = new(string.Empty, string.Empty, ObjectiveType.DropRequirements, string.Empty, null);
    private Task Audit(string action, Guid tileId, string details, CancellationToken ct) => auditWriter.WriteAsync(User.GetAccountId(), User.Identity!.Name!, action, "tile_template", tileId.ToString(), details, ct);
    public sealed class RequirementInput { [Required, StringLength(2000)] public string Description { get; set; } = string.Empty; [Range(1, 10000)] public int Target { get; set; } = 1; public bool Manual { get; set; } public bool DuplicatesAllowed { get; set; } = true; public bool AllowHigherWeightings { get; set; } [Display(Name = "Bosses or activities")] public List<Guid> BossIds { get; set; } = []; [Display(Name = "Eligible drops")] public List<Guid> DropIds { get; set; } = []; }
    public sealed record BossRow(Guid Id, string Name); public sealed record DropRow(Guid Id, string Boss, string Item, string Rate); public sealed record RequirementRow(Guid Id, int Position, string Description, int Target, bool Manual, bool DuplicatesAllowed, bool HigherWeights, decimal? Ehb); public sealed record TileMetadata(string Name, string Description, ObjectiveType ObjectiveType, string EvidenceInstructions, decimal? ManualEhb);
}
