namespace Bingo.Infrastructure.WiseOldMan;

// Request names and direct score mapping checked against WOM adde6ac93b8a631e58f02384c28e8d98f0061812.
// A successful response must still supply every requested character/metric; this list is not coverage proof.
public static class CompetitionMetricContract
{
    public static IReadOnlySet<string> SupportedMetrics { get; } = new HashSet<string>(StringComparer.Ordinal)
    {
        "abyssal_sire",
        "alchemical_hydra",
        "amoxliatl",
        "araxxor",
        "artio",
        "barrows_chests",
        "brutus",
        "bryophyta",
        "callisto",
        "calvarion",
        "cerberus",
        "chambers_of_xeric",
        "chambers_of_xeric_challenge_mode",
        "chaos_elemental",
        "chaos_fanatic",
        "commander_zilyana",
        "corporeal_beast",
        "crazy_archaeologist",
        "dagannoth_prime",
        "dagannoth_rex",
        "dagannoth_supreme",
        "deranged_archaeologist",
        "doom_of_mokhaiotl",
        "duke_sucellus",
        "general_graardor",
        "giant_mole",
        "grotesque_guardians",
        "hespori",
        "kalphite_queen",
        "king_black_dragon",
        "kraken",
        "kreearra",
        "kril_tsutsaroth",
        "lunar_chests",
        "mad_angel",
        "maggot_king",
        "mimic",
        "nex",
        "nightmare",
        "phosanis_nightmare",
        "obor",
        "phantom_muspah",
        "sarachnis",
        "scorpia",
        "scurrius",
        "shellbane_gryphon",
        "skotizo",
        "sol_heredit",
        "spindel",
        "tempoross",
        "the_gauntlet",
        "the_corrupted_gauntlet",
        "the_hueycoatl",
        "the_leviathan",
        "the_royal_titans",
        "the_whisperer",
        "theatre_of_blood",
        "theatre_of_blood_hard_mode",
        "thermonuclear_smoke_devil",
        "tombs_of_amascut",
        "tombs_of_amascut_expert",
        "tzkal_zuk",
        "tztok_jad",
        "vardorvis",
        "venenatis",
        "vetion",
        "vorkath",
        "wintertodt",
        "yama",
        "zalcano",
        "zulrah",
    };

    public static string? UnavailableReason(string? metric) => metric is null ? "Unmapped"
        : !SupportedMetrics.Contains(metric) ? "UnverifiedMetric" : null;
}
