using Bingo.Domain.Boards;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Bingo.Infrastructure.Persistence.Configurations;

public sealed class BoardConfiguration : IEntityTypeConfiguration<Board>
{
    public void Configure(EntityTypeBuilder<Board> builder) { builder.ToTable("boards"); builder.HasKey(x => x.Id); builder.Property(x => x.Id).HasColumnName("id"); builder.Property(x => x.EventId).HasColumnName("event_id"); builder.HasIndex(x => x.EventId).IsUnique(); builder.Property(x => x.Name).HasColumnName("name").HasMaxLength(200); builder.Property(x => x.Rows).HasColumnName("rows"); builder.Property(x => x.Columns).HasColumnName("columns"); builder.Property(x => x.State).HasColumnName("state").HasConversion<string>().HasMaxLength(30); builder.Property(x => x.PublishedAt).HasColumnName("published_at"); builder.Property(x => x.TotalEhbEstimate).HasColumnName("total_ehb_estimate").HasPrecision(14, 4); builder.Property(x => x.CalculationVersion).HasColumnName("calculation_version"); builder.Property(x => x.Version).HasColumnName("version").IsConcurrencyToken(); builder.Property(x => x.EditorAccountId).HasColumnName("editor_account_id"); builder.Property(x => x.EditorLeaseExpiresAt).HasColumnName("editor_lease_expires_at"); builder.Property(x => x.EditControlVersion).HasColumnName("edit_control_version").IsConcurrencyToken(); }
}
public sealed class TileTemplateConfiguration : IEntityTypeConfiguration<TileTemplate> { public void Configure(EntityTypeBuilder<TileTemplate> builder) { builder.ToTable("tile_templates"); builder.HasKey(x => x.Id); builder.Property(x => x.Id).HasColumnName("id"); builder.Property(x => x.Name).HasColumnName("name").HasMaxLength(200); builder.Property(x => x.Description).HasColumnName("description").HasMaxLength(4000); builder.Property(x => x.ObjectiveType).HasColumnName("objective_type").HasConversion<string>().HasMaxLength(30); builder.Property(x => x.EvidenceInstructions).HasColumnName("evidence_instructions").HasMaxLength(4000); builder.Property(x => x.ManualEhbOverride).HasColumnName("manual_ehb_override").HasPrecision(12, 4); builder.Property(x => x.ImageUrl).HasColumnName("image_url").HasMaxLength(2000); builder.Property(x => x.Active).HasColumnName("active"); } }
public sealed class TileTemplateRequirementConfiguration : IEntityTypeConfiguration<TileTemplateRequirement> { public void Configure(EntityTypeBuilder<TileTemplateRequirement> builder) { builder.ToTable("tile_template_requirements"); builder.HasKey(x => x.Id); builder.Property(x => x.Id).HasColumnName("id"); builder.Property(x => x.TileTemplateId).HasColumnName("tile_template_id"); builder.Property(x => x.Position).HasColumnName("position"); builder.HasIndex(x => new { x.TileTemplateId, x.Position }).IsUnique(); builder.Property(x => x.TargetContribution).HasColumnName("target_contribution"); builder.Property(x => x.DuplicatesAllowed).HasColumnName("duplicates_allowed"); builder.Property(x => x.AllowHigherWeightings).HasColumnName("allow_higher_weightings"); builder.Property(x => x.CreditedWeight).HasColumnName("credited_weight").HasDefaultValue(1); builder.Property(x => x.Description).HasColumnName("description").HasMaxLength(2000); builder.Property(x => x.ManualObjective).HasColumnName("manual_objective"); } }
public sealed class TemplateRequirementBossConfiguration : IEntityTypeConfiguration<TemplateRequirementBoss> { public void Configure(EntityTypeBuilder<TemplateRequirementBoss> builder) { builder.ToTable("template_requirement_bosses"); builder.HasKey(x => x.Id); builder.Property(x => x.Id).HasColumnName("id"); builder.Property(x => x.RequirementId).HasColumnName("requirement_id"); builder.Property(x => x.BossActivityId).HasColumnName("boss_activity_id"); builder.HasIndex(x => new { x.RequirementId, x.BossActivityId }).IsUnique(); } }
public sealed class TemplateRequirementDropConfiguration : IEntityTypeConfiguration<TemplateRequirementDrop> { public void Configure(EntityTypeBuilder<TemplateRequirementDrop> builder) { builder.ToTable("template_requirement_drops"); builder.HasKey(x => x.Id); builder.Property(x => x.Id).HasColumnName("id"); builder.Property(x => x.RequirementId).HasColumnName("requirement_id"); builder.Property(x => x.SourceDropId).HasColumnName("source_drop_id"); builder.Property(x => x.MaximumContribution).HasColumnName("maximum_contribution"); builder.Property(x => x.CreditedWeight).HasColumnName("credited_weight").HasDefaultValue(1); builder.HasIndex(x => new { x.RequirementId, x.SourceDropId }).IsUnique(); } }
public sealed class BoardTileConfiguration : IEntityTypeConfiguration<BoardTile> { public void Configure(EntityTypeBuilder<BoardTile> builder) { builder.ToTable("board_tiles"); builder.HasKey(x => x.Id); builder.Property(x => x.Id).HasColumnName("id"); builder.Property(x => x.BoardId).HasColumnName("board_id"); builder.Property(x => x.TileTemplateId).HasColumnName("tile_template_id"); builder.Property(x => x.RowIndex).HasColumnName("row_index"); builder.Property(x => x.ColumnIndex).HasColumnName("column_index"); builder.HasIndex(x => new { x.BoardId, x.RowIndex, x.ColumnIndex }).IsUnique(); builder.Property(x => x.NameSnapshot).HasColumnName("name_snapshot").HasMaxLength(200); builder.Property(x => x.DescriptionSnapshot).HasColumnName("description_snapshot").HasMaxLength(4000); builder.Property(x => x.EvidenceInstructionsSnapshot).HasColumnName("evidence_instructions_snapshot").HasMaxLength(4000); builder.Property(x => x.EstimatedEhbSnapshot).HasColumnName("estimated_ehb_snapshot").HasPrecision(12, 4); builder.Property(x => x.ImageUrlSnapshot).HasColumnName("image_url_snapshot").HasMaxLength(2000); } }
public sealed class BoardRequirementSnapshotConfiguration : IEntityTypeConfiguration<BoardRequirementSnapshot> { public void Configure(EntityTypeBuilder<BoardRequirementSnapshot> builder) { builder.ToTable("board_requirement_snapshots"); builder.HasKey(x => x.Id); builder.Property(x => x.Id).HasColumnName("id"); builder.Property(x => x.BoardTileId).HasColumnName("board_tile_id"); builder.Property(x => x.Position).HasColumnName("position"); builder.Property(x => x.TargetContribution).HasColumnName("target_contribution"); builder.Property(x => x.DuplicatesAllowed).HasColumnName("duplicates_allowed"); builder.Property(x => x.AllowHigherWeightings).HasColumnName("allow_higher_weightings"); builder.Property(x => x.CreditedWeight).HasColumnName("credited_weight").HasDefaultValue(1); builder.Property(x => x.Description).HasColumnName("description").HasMaxLength(2000); builder.Property(x => x.ManualObjective).HasColumnName("manual_objective"); } }
public sealed class BoardRequirementBossSnapshotConfiguration : IEntityTypeConfiguration<BoardRequirementBossSnapshot> { public void Configure(EntityTypeBuilder<BoardRequirementBossSnapshot> builder) { builder.ToTable("board_requirement_boss_snapshots"); builder.HasKey(x => x.Id); builder.Property(x => x.Id).HasColumnName("id"); builder.Property(x => x.RequirementId).HasColumnName("requirement_id"); builder.Property(x => x.BossActivityId).HasColumnName("boss_activity_id"); builder.Property(x => x.BossName).HasColumnName("boss_name").HasMaxLength(200); builder.Property(x => x.EfficientRate).HasColumnName("efficient_rate").HasPrecision(12, 4); } }
public sealed class BoardRequirementDropSnapshotConfiguration : IEntityTypeConfiguration<BoardRequirementDropSnapshot> { public void Configure(EntityTypeBuilder<BoardRequirementDropSnapshot> builder) { builder.ToTable("board_requirement_drop_snapshots"); builder.HasKey(x => x.Id); builder.Property(x => x.Id).HasColumnName("id"); builder.Property(x => x.RequirementId).HasColumnName("requirement_id"); builder.Property(x => x.SourceDropId).HasColumnName("source_drop_id"); builder.Property(x => x.BossName).HasColumnName("boss_name").HasMaxLength(200); builder.Property(x => x.ItemName).HasColumnName("item_name").HasMaxLength(200); builder.Property(x => x.DisplayRate).HasColumnName("display_rate").HasMaxLength(200); builder.Property(x => x.NumericProbability).HasColumnName("numeric_probability").HasPrecision(18, 12); builder.Property(x => x.MaximumContribution).HasColumnName("maximum_contribution"); builder.Property(x => x.EhbPerContribution).HasColumnName("ehb_per_contribution").HasPrecision(12, 4); builder.Property(x => x.CreditedWeight).HasColumnName("credited_weight").HasDefaultValue(1); } }
