using Bingo.Domain.Boards;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Bingo.Infrastructure.Persistence.Configurations;

public sealed class BoardConfiguration : IEntityTypeConfiguration<Board>
{
    public void Configure(EntityTypeBuilder<Board> builder)
    {
        builder.ToTable("boards"); builder.HasKey(x => x.Id); builder.Property(x => x.Id).HasColumnName("id"); builder.Property(x => x.EventId).HasColumnName("event_id"); builder.HasIndex(x => x.EventId).IsUnique(); builder.Property(x => x.Name).HasColumnName("name").HasMaxLength(200); builder.Property(x => x.Rows).HasColumnName("rows"); builder.Property(x => x.Columns).HasColumnName("columns"); builder.Property(x => x.State).HasColumnName("state").HasConversion<string>().HasMaxLength(30); builder.Property(x => x.PublishedAt).HasColumnName("published_at"); builder.Property(x => x.TotalEhbEstimate).HasColumnName("total_ehb_estimate").HasPrecision(14, 4); builder.Property(x => x.CalculationVersion).HasColumnName("calculation_version"); builder.Property(x => x.Version).HasColumnName("version").IsConcurrencyToken(); builder.Property(x => x.ActiveApprovalSnapshotId).HasColumnName("active_approval_snapshot_id"); builder.Property(x => x.PublishedCorrectionInProgress).HasColumnName("published_correction_in_progress"); builder.Property(x => x.EditorAccountId).HasColumnName("editor_account_id"); builder.Property(x => x.EditorLeaseExpiresAt).HasColumnName("editor_lease_expires_at"); builder.Property(x => x.EditControlVersion).HasColumnName("edit_control_version").IsConcurrencyToken();
        builder.HasOne<BoardApprovalSnapshot>().WithMany().HasForeignKey(x => x.ActiveApprovalSnapshotId).OnDelete(DeleteBehavior.SetNull);
    }
}
public sealed class TileTemplateConfiguration : IEntityTypeConfiguration<TileTemplate> { public void Configure(EntityTypeBuilder<TileTemplate> builder) { builder.ToTable("tile_templates"); builder.HasKey(x => x.Id); builder.Property(x => x.Id).HasColumnName("id"); builder.Property(x => x.Name).HasColumnName("name").HasMaxLength(200); builder.Property(x => x.Description).HasColumnName("description").HasMaxLength(4000); builder.Property(x => x.ObjectiveType).HasColumnName("objective_type").HasConversion<string>().HasMaxLength(30); builder.Property(x => x.EvidenceInstructions).HasColumnName("evidence_instructions").HasMaxLength(4000); builder.Property(x => x.ManualEhbOverride).HasColumnName("manual_ehb_override").HasPrecision(12, 4); builder.Property(x => x.ImageUrl).HasColumnName("image_url").HasMaxLength(2000); builder.Property(x => x.Active).HasColumnName("active"); } }
public sealed class TileTemplateRequirementConfiguration : IEntityTypeConfiguration<TileTemplateRequirement> { public void Configure(EntityTypeBuilder<TileTemplateRequirement> builder) { builder.ToTable("tile_template_requirements"); builder.HasKey(x => x.Id); builder.Property(x => x.Id).HasColumnName("id"); builder.Property(x => x.TileTemplateId).HasColumnName("tile_template_id"); builder.Property(x => x.Position).HasColumnName("position"); builder.HasIndex(x => new { x.TileTemplateId, x.Position }).IsUnique(); builder.Property(x => x.TargetContribution).HasColumnName("target_contribution"); builder.Property(x => x.DuplicatesAllowed).HasColumnName("duplicates_allowed"); builder.Property(x => x.AllowHigherWeightings).HasColumnName("allow_higher_weightings"); builder.Property(x => x.CreditedWeight).HasColumnName("credited_weight").HasDefaultValue(1); builder.Property(x => x.Description).HasColumnName("description").HasMaxLength(2000); builder.Property(x => x.ManualObjective).HasColumnName("manual_objective"); } }
public sealed class TemplateRequirementBossConfiguration : IEntityTypeConfiguration<TemplateRequirementBoss> { public void Configure(EntityTypeBuilder<TemplateRequirementBoss> builder) { builder.ToTable("template_requirement_bosses"); builder.HasKey(x => x.Id); builder.Property(x => x.Id).HasColumnName("id"); builder.Property(x => x.RequirementId).HasColumnName("requirement_id"); builder.Property(x => x.BossActivityId).HasColumnName("boss_activity_id"); builder.HasIndex(x => new { x.RequirementId, x.BossActivityId }).IsUnique(); } }
public sealed class TemplateRequirementDropConfiguration : IEntityTypeConfiguration<TemplateRequirementDrop> { public void Configure(EntityTypeBuilder<TemplateRequirementDrop> builder) { builder.ToTable("template_requirement_drops"); builder.HasKey(x => x.Id); builder.Property(x => x.Id).HasColumnName("id"); builder.Property(x => x.RequirementId).HasColumnName("requirement_id"); builder.Property(x => x.SourceDropId).HasColumnName("source_drop_id"); builder.Property(x => x.MaximumContribution).HasColumnName("maximum_contribution"); builder.Property(x => x.CreditedWeight).HasColumnName("credited_weight").HasDefaultValue(1); builder.HasIndex(x => new { x.RequirementId, x.SourceDropId }).IsUnique(); } }
public sealed class BoardTileConfiguration : IEntityTypeConfiguration<BoardTile> { public void Configure(EntityTypeBuilder<BoardTile> builder) { builder.ToTable("board_tiles"); builder.HasKey(x => x.Id); builder.Property(x => x.Id).HasColumnName("id"); builder.Property(x => x.BoardId).HasColumnName("board_id"); builder.Property(x => x.TileTemplateId).HasColumnName("tile_template_id"); builder.Property(x => x.RowIndex).HasColumnName("row_index"); builder.Property(x => x.ColumnIndex).HasColumnName("column_index"); builder.HasIndex(x => new { x.BoardId, x.RowIndex, x.ColumnIndex }).IsUnique(); builder.Property(x => x.NameSnapshot).HasColumnName("name_snapshot").HasMaxLength(200); builder.Property(x => x.DescriptionSnapshot).HasColumnName("description_snapshot").HasMaxLength(4000); builder.Property(x => x.EvidenceInstructionsSnapshot).HasColumnName("evidence_instructions_snapshot").HasMaxLength(4000); builder.Property(x => x.EstimatedEhbSnapshot).HasColumnName("estimated_ehb_snapshot").HasPrecision(12, 4); builder.Property(x => x.ImageUrlSnapshot).HasColumnName("image_url_snapshot").HasMaxLength(2000); builder.Property(x => x.ActiveImageAssetId).HasColumnName("active_image_asset_id"); builder.HasOne<BoardTileImageAsset>().WithMany().HasForeignKey(x => x.ActiveImageAssetId).OnDelete(DeleteBehavior.SetNull); } }
public sealed class BoardTileImageAssetConfiguration : IEntityTypeConfiguration<BoardTileImageAsset> { public void Configure(EntityTypeBuilder<BoardTileImageAsset> builder) { builder.ToTable("board_tile_image_assets"); builder.HasKey(x => x.Id); builder.Property(x => x.Id).HasColumnName("id"); builder.Property(x => x.EventId).HasColumnName("event_id"); builder.Property(x => x.BoardTileId).HasColumnName("board_tile_id"); builder.Property(x => x.StorageKey).HasColumnName("storage_key").HasMaxLength(500); builder.Property(x => x.OriginalFilename).HasColumnName("original_filename").HasMaxLength(255); builder.Property(x => x.MediaType).HasColumnName("media_type").HasMaxLength(100); builder.Property(x => x.ByteSize).HasColumnName("byte_size"); builder.Property(x => x.Width).HasColumnName("width"); builder.Property(x => x.Height).HasColumnName("height"); builder.Property(x => x.Checksum).HasColumnName("checksum").HasMaxLength(64); builder.Property(x => x.UploadedByAccountId).HasColumnName("uploaded_by_account_id"); builder.Property(x => x.UploadedAt).HasColumnName("uploaded_at"); builder.Property(x => x.ReplacedAt).HasColumnName("replaced_at"); builder.HasIndex(x => new { x.BoardTileId, x.ReplacedAt }); builder.HasOne<BoardTile>().WithMany().HasForeignKey(x => x.BoardTileId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class BoardRequirementSnapshotConfiguration : IEntityTypeConfiguration<BoardRequirementSnapshot> { public void Configure(EntityTypeBuilder<BoardRequirementSnapshot> builder) { builder.ToTable("board_requirement_snapshots"); builder.HasKey(x => x.Id); builder.Property(x => x.Id).HasColumnName("id"); builder.Property(x => x.BoardTileId).HasColumnName("board_tile_id"); builder.Property(x => x.Position).HasColumnName("position"); builder.Property(x => x.TargetContribution).HasColumnName("target_contribution"); builder.Property(x => x.DuplicatesAllowed).HasColumnName("duplicates_allowed"); builder.Property(x => x.AllowHigherWeightings).HasColumnName("allow_higher_weightings"); builder.Property(x => x.CreditedWeight).HasColumnName("credited_weight").HasDefaultValue(1); builder.Property(x => x.Description).HasColumnName("description").HasMaxLength(2000); builder.Property(x => x.ManualObjective).HasColumnName("manual_objective"); } }
public sealed class BoardRequirementBossSnapshotConfiguration : IEntityTypeConfiguration<BoardRequirementBossSnapshot> { public void Configure(EntityTypeBuilder<BoardRequirementBossSnapshot> builder) { builder.ToTable("board_requirement_boss_snapshots"); builder.HasKey(x => x.Id); builder.Property(x => x.Id).HasColumnName("id"); builder.Property(x => x.RequirementId).HasColumnName("requirement_id"); builder.Property(x => x.BossActivityId).HasColumnName("boss_activity_id"); builder.Property(x => x.BossName).HasColumnName("boss_name").HasMaxLength(200); builder.Property(x => x.EfficientRate).HasColumnName("efficient_rate").HasPrecision(12, 4); } }
public sealed class BoardRequirementDropSnapshotConfiguration : IEntityTypeConfiguration<BoardRequirementDropSnapshot> { public void Configure(EntityTypeBuilder<BoardRequirementDropSnapshot> builder) { builder.ToTable("board_requirement_drop_snapshots"); builder.HasKey(x => x.Id); builder.Property(x => x.Id).HasColumnName("id"); builder.Property(x => x.RequirementId).HasColumnName("requirement_id"); builder.Property(x => x.SourceDropId).HasColumnName("source_drop_id"); builder.Property(x => x.ItemIdSnapshot).HasColumnName("item_id_snapshot"); builder.Property(x => x.BossName).HasColumnName("boss_name").HasMaxLength(200); builder.Property(x => x.ItemName).HasColumnName("item_name").HasMaxLength(200); builder.Property(x => x.DisplayRate).HasColumnName("display_rate").HasMaxLength(200); builder.Property(x => x.NumericProbability).HasColumnName("numeric_probability").HasPrecision(18, 12); builder.Property(x => x.MaximumContribution).HasColumnName("maximum_contribution"); builder.Property(x => x.EhbPerContribution).HasColumnName("ehb_per_contribution").HasPrecision(12, 4); builder.Property(x => x.CreditedWeight).HasColumnName("credited_weight").HasDefaultValue(1); } }
public sealed class BoardApprovalSnapshotConfiguration : IEntityTypeConfiguration<BoardApprovalSnapshot>
{
    public void Configure(EntityTypeBuilder<BoardApprovalSnapshot> builder)
    {
        builder.ToTable("board_approval_snapshots"); builder.HasKey(x => x.Id); builder.Property(x => x.Id).HasColumnName("id"); builder.Property(x => x.BoardId).HasColumnName("board_id"); builder.Property(x => x.Version).HasColumnName("version"); builder.HasIndex(x => new { x.BoardId, x.Version }).IsUnique(); builder.Property(x => x.ApprovedAt).HasColumnName("approved_at"); builder.Property(x => x.ApprovedByAccountId).HasColumnName("approved_by_account_id"); builder.Property(x => x.SupersedesApprovalSnapshotId).HasColumnName("supersedes_approval_snapshot_id"); builder.Property(x => x.Name).HasColumnName("name").HasMaxLength(200); builder.Property(x => x.Rows).HasColumnName("rows"); builder.Property(x => x.Columns).HasColumnName("columns"); builder.Property(x => x.TotalEhbEstimate).HasColumnName("total_ehb_estimate").HasPrecision(14, 4); builder.Property(x => x.CalculationVersion).HasColumnName("calculation_version"); builder.Property(x => x.BoardVersion).HasColumnName("board_version"); builder.Property(x => x.LifecycleState).HasColumnName("lifecycle_state").HasConversion<string>().HasMaxLength(30);
        builder.HasOne<Board>().WithMany().HasForeignKey(x => x.BoardId).OnDelete(DeleteBehavior.Cascade);
        builder.HasOne<BoardApprovalSnapshot>().WithMany().HasForeignKey(x => x.SupersedesApprovalSnapshotId).OnDelete(DeleteBehavior.Restrict);
    }
}
public sealed class BoardApprovalTileSnapshotConfiguration : IEntityTypeConfiguration<BoardApprovalTileSnapshot>
{
    public void Configure(EntityTypeBuilder<BoardApprovalTileSnapshot> builder)
    {
        builder.ToTable("board_approval_tile_snapshots"); builder.HasKey(x => x.Id); builder.Property(x => x.Id).HasColumnName("id"); builder.Property(x => x.ApprovalSnapshotId).HasColumnName("approval_snapshot_id"); builder.Property(x => x.BoardTileId).HasColumnName("board_tile_id"); builder.HasIndex(x => new { x.ApprovalSnapshotId, x.BoardTileId }).IsUnique(); builder.Property(x => x.TileTemplateId).HasColumnName("tile_template_id"); builder.Property(x => x.RowIndex).HasColumnName("row_index"); builder.Property(x => x.ColumnIndex).HasColumnName("column_index"); builder.HasIndex(x => new { x.ApprovalSnapshotId, x.RowIndex, x.ColumnIndex }).IsUnique(); builder.Property(x => x.Name).HasColumnName("name").HasMaxLength(200); builder.Property(x => x.Description).HasColumnName("description").HasMaxLength(4000); builder.Property(x => x.EvidenceInstructions).HasColumnName("evidence_instructions").HasMaxLength(4000); builder.Property(x => x.EstimatedEhb).HasColumnName("estimated_ehb").HasPrecision(12, 4); builder.Property(x => x.ArtworkReference).HasColumnName("artwork_reference").HasMaxLength(2000);
        builder.HasOne<BoardApprovalSnapshot>().WithMany().HasForeignKey(x => x.ApprovalSnapshotId).OnDelete(DeleteBehavior.Cascade);
    }
}
public sealed class BoardApprovalRequirementSnapshotConfiguration : IEntityTypeConfiguration<BoardApprovalRequirementSnapshot>
{
    public void Configure(EntityTypeBuilder<BoardApprovalRequirementSnapshot> builder)
    {
        builder.ToTable("board_approval_requirement_snapshots"); builder.HasKey(x => x.Id); builder.Property(x => x.Id).HasColumnName("id"); builder.Property(x => x.ApprovalTileSnapshotId).HasColumnName("approval_tile_snapshot_id"); builder.Property(x => x.BoardRequirementSnapshotId).HasColumnName("board_requirement_snapshot_id"); builder.HasIndex(x => new { x.ApprovalTileSnapshotId, x.BoardRequirementSnapshotId }).IsUnique(); builder.Property(x => x.Position).HasColumnName("position"); builder.HasIndex(x => new { x.ApprovalTileSnapshotId, x.Position }).IsUnique(); builder.Property(x => x.TargetContribution).HasColumnName("target_contribution"); builder.Property(x => x.DuplicatesAllowed).HasColumnName("duplicates_allowed"); builder.Property(x => x.AllowHigherWeightings).HasColumnName("allow_higher_weightings"); builder.Property(x => x.CreditedWeight).HasColumnName("credited_weight"); builder.Property(x => x.Description).HasColumnName("description").HasMaxLength(2000); builder.Property(x => x.ManualObjective).HasColumnName("manual_objective");
        builder.HasOne<BoardApprovalTileSnapshot>().WithMany().HasForeignKey(x => x.ApprovalTileSnapshotId).OnDelete(DeleteBehavior.Cascade);
    }
}
public sealed class BoardApprovalRequirementBossSnapshotConfiguration : IEntityTypeConfiguration<BoardApprovalRequirementBossSnapshot>
{
    public void Configure(EntityTypeBuilder<BoardApprovalRequirementBossSnapshot> builder)
    {
        builder.ToTable("board_approval_requirement_boss_snapshots"); builder.HasKey(x => x.Id); builder.Property(x => x.Id).HasColumnName("id"); builder.Property(x => x.ApprovalRequirementSnapshotId).HasColumnName("approval_requirement_snapshot_id"); builder.Property(x => x.BossActivityId).HasColumnName("boss_activity_id"); builder.HasIndex(x => new { x.ApprovalRequirementSnapshotId, x.BossActivityId }).IsUnique(); builder.Property(x => x.Name).HasColumnName("name").HasMaxLength(200); builder.Property(x => x.EfficientRate).HasColumnName("efficient_rate").HasPrecision(12, 4); builder.Property(x => x.CatalogueVersion).HasColumnName("catalogue_version");
        builder.HasOne<BoardApprovalRequirementSnapshot>().WithMany().HasForeignKey(x => x.ApprovalRequirementSnapshotId).OnDelete(DeleteBehavior.Cascade);
    }
}
public sealed class BoardApprovalRequirementDropSnapshotConfiguration : IEntityTypeConfiguration<BoardApprovalRequirementDropSnapshot>
{
    public void Configure(EntityTypeBuilder<BoardApprovalRequirementDropSnapshot> builder)
    {
        builder.ToTable("board_approval_requirement_drop_snapshots"); builder.HasKey(x => x.Id); builder.Property(x => x.Id).HasColumnName("id"); builder.Property(x => x.ApprovalRequirementSnapshotId).HasColumnName("approval_requirement_snapshot_id"); builder.Property(x => x.SourceDropId).HasColumnName("source_drop_id"); builder.Property(x => x.ItemIdSnapshot).HasColumnName("item_id_snapshot"); builder.HasIndex(x => new { x.ApprovalRequirementSnapshotId, x.SourceDropId }); builder.Property(x => x.BossName).HasColumnName("boss_name").HasMaxLength(200); builder.Property(x => x.ItemName).HasColumnName("item_name").HasMaxLength(200); builder.Property(x => x.DisplayRate).HasColumnName("display_rate").HasMaxLength(200); builder.Property(x => x.NumericProbability).HasColumnName("numeric_probability").HasPrecision(18, 12); builder.Property(x => x.ProbabilityScope).HasColumnName("probability_scope").HasConversion<string>().HasMaxLength(20); builder.Property(x => x.ConditionalOnParent).HasColumnName("conditional_on_parent"); builder.Property(x => x.ParentProbability).HasColumnName("parent_probability").HasPrecision(18, 12); builder.Property(x => x.AssumedParticipants).HasColumnName("assumed_participants"); builder.Property(x => x.RollsPerCompletion).HasColumnName("rolls_per_completion"); builder.Property(x => x.RollGroup).HasColumnName("roll_group").HasMaxLength(120); builder.Property(x => x.RateCondition).HasColumnName("rate_condition").HasMaxLength(2000); builder.Property(x => x.MaximumContribution).HasColumnName("maximum_contribution"); builder.Property(x => x.EhbPerContribution).HasColumnName("ehb_per_contribution").HasPrecision(12, 4); builder.Property(x => x.CreditedWeight).HasColumnName("credited_weight"); builder.Property(x => x.CatalogueVersion).HasColumnName("catalogue_version");
        builder.HasOne<BoardApprovalRequirementSnapshot>().WithMany().HasForeignKey(x => x.ApprovalRequirementSnapshotId).OnDelete(DeleteBehavior.Cascade);
    }
}
