using Bingo.Domain.Evidence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Bingo.Infrastructure.Persistence.Configurations;

public sealed class EvidenceCodeConfiguration : IEntityTypeConfiguration<EvidenceCode>
{
    public void Configure(EntityTypeBuilder<EvidenceCode> builder) { builder.ToTable("evidence_codes");builder.HasKey(x=>x.Id);builder.Property(x=>x.Id).HasColumnName("id");builder.Property(x=>x.EventId).HasColumnName("event_id");builder.Property(x=>x.Code).HasColumnName("code").HasMaxLength(100);builder.Property(x=>x.ActivatesAt).HasColumnName("activates_at");builder.Property(x=>x.RetiresAt).HasColumnName("retires_at");builder.Property(x=>x.CreatedByAccountId).HasColumnName("created_by_account_id");builder.Property(x=>x.CreatedAt).HasColumnName("created_at");builder.Property(x=>x.Note).HasColumnName("note").HasMaxLength(1000);builder.HasIndex(x=>new{x.EventId,x.ActivatesAt}); }
}
public sealed class SubmissionConfiguration : IEntityTypeConfiguration<Submission>
{
    public void Configure(EntityTypeBuilder<Submission> builder) { builder.ToTable("submissions");builder.HasKey(x=>x.Id);builder.Property(x=>x.Id).HasColumnName("id");builder.Property(x=>x.EventId).HasColumnName("event_id");builder.Property(x=>x.TeamId).HasColumnName("team_id");builder.Property(x=>x.BoardTileId).HasColumnName("board_tile_id");builder.Property(x=>x.RequirementId).HasColumnName("requirement_id");builder.Property(x=>x.DropSnapshotId).HasColumnName("drop_snapshot_id");builder.Property(x=>x.CreditedParticipantId).HasColumnName("credited_participant_id");builder.Property(x=>x.SubmittedByAccountId).HasColumnName("submitted_by_account_id");builder.Property(x=>x.ClaimedWeight).HasColumnName("claimed_weight");builder.Property(x=>x.ApprovedContribution).HasColumnName("approved_contribution");builder.Property(x=>x.SubmittedAt).HasColumnName("submitted_at");builder.Property(x=>x.CaptainNote).HasColumnName("captain_note").HasMaxLength(4000);builder.Property(x=>x.Status).HasColumnName("status").HasConversion<string>().HasMaxLength(30);builder.Property(x=>x.PublicEvidenceHidden).HasColumnName("public_evidence_hidden");builder.Property(x=>x.PublicPlayerHidden).HasColumnName("public_player_hidden");builder.Property(x=>x.PublicPrivacyRequested).HasColumnName("public_privacy_requested");builder.Property(x=>x.ExpectedEvidenceCode).HasColumnName("expected_evidence_code").HasMaxLength(100);builder.Property(x=>x.CurrentReviewerNote).HasColumnName("current_reviewer_note").HasMaxLength(4000);builder.Property(x=>x.DuplicateOfSubmissionId).HasColumnName("duplicate_of_submission_id");builder.Property(x=>x.ReviewedAt).HasColumnName("reviewed_at");builder.HasIndex(x=>new{x.EventId,x.Status,x.SubmittedAt});builder.HasIndex(x=>new{x.TeamId,x.SubmittedAt}); }
}
public sealed class EvidenceAssetConfiguration : IEntityTypeConfiguration<EvidenceAsset>
{
    public void Configure(EntityTypeBuilder<EvidenceAsset> builder) { builder.ToTable("evidence_assets");builder.HasKey(x=>x.Id);builder.Property(x=>x.Id).HasColumnName("id");builder.Property(x=>x.SubmissionId).HasColumnName("submission_id");builder.Property(x=>x.StorageKey).HasColumnName("storage_key").HasMaxLength(500);builder.Property(x=>x.OriginalFilename).HasColumnName("original_filename").HasMaxLength(255);builder.Property(x=>x.MediaType).HasColumnName("media_type").HasMaxLength(100);builder.Property(x=>x.ByteSize).HasColumnName("byte_size");builder.Property(x=>x.PixelWidth).HasColumnName("pixel_width");builder.Property(x=>x.PixelHeight).HasColumnName("pixel_height");builder.Property(x=>x.Checksum).HasColumnName("checksum").HasMaxLength(64);builder.Property(x=>x.UploadedAt).HasColumnName("uploaded_at");builder.Property(x=>x.UploadedByAccountId).HasColumnName("uploaded_by_account_id");builder.Property(x=>x.Role).HasColumnName("role").HasConversion<string>().HasMaxLength(40);builder.Property(x=>x.Active).HasColumnName("active");builder.HasIndex(x=>new{x.SubmissionId,x.Active});builder.HasIndex(x=>x.Checksum); }
}
public sealed class ReviewActionConfiguration : IEntityTypeConfiguration<ReviewAction>
{
    public void Configure(EntityTypeBuilder<ReviewAction> builder) { builder.ToTable("review_actions");builder.HasKey(x=>x.Id);builder.Property(x=>x.Id).HasColumnName("id");builder.Property(x=>x.SubmissionId).HasColumnName("submission_id");builder.Property(x=>x.Action).HasColumnName("action").HasConversion<string>().HasMaxLength(40);builder.Property(x=>x.PerformedByAccountId).HasColumnName("performed_by_account_id");builder.Property(x=>x.PerformedAt).HasColumnName("performed_at");builder.Property(x=>x.Note).HasColumnName("note").HasMaxLength(4000);builder.Property(x=>x.BeforeSnapshot).HasColumnName("before_snapshot").HasColumnType("jsonb");builder.Property(x=>x.AfterSnapshot).HasColumnName("after_snapshot").HasColumnType("jsonb");builder.HasIndex(x=>new{x.SubmissionId,x.PerformedAt}); }
}
public sealed class SubmissionContributionConfiguration : IEntityTypeConfiguration<SubmissionContribution>
{
    public void Configure(EntityTypeBuilder<SubmissionContribution> builder) { builder.ToTable("submission_contributions");builder.HasKey(x=>x.Id);builder.Property(x=>x.Id).HasColumnName("id");builder.Property(x=>x.SubmissionId).HasColumnName("submission_id");builder.HasIndex(x=>x.SubmissionId).IsUnique();builder.Property(x=>x.TeamId).HasColumnName("team_id");builder.Property(x=>x.RequirementId).HasColumnName("requirement_id");builder.Property(x=>x.DropSnapshotId).HasColumnName("drop_snapshot_id");builder.Property(x=>x.CreditedParticipantId).HasColumnName("credited_participant_id");builder.Property(x=>x.Amount).HasColumnName("amount");builder.Property(x=>x.AppliedAt).HasColumnName("applied_at");builder.Property(x=>x.ReversedAt).HasColumnName("reversed_at");builder.HasIndex(x=>new{x.TeamId,x.RequirementId,x.ReversedAt}); }
}
