using System.ComponentModel.DataAnnotations;
using Bingo.Application.Evidence;
using Bingo.Domain.Evidence;
using Bingo.Infrastructure.Persistence;
using Bingo.Web.Security;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Bingo.Web.Pages.Admin.Review;

public sealed class DetailsModel(ApplicationDbContext db,ISubmissionService service) : PageModel
{
    public DetailsView Details{get;private set;}=null!;public IReadOnlyList<AssetView>Assets{get;private set;}=[];public IReadOnlyList<ActionView>History{get;private set;}=[];public IReadOnlyList<ContextView>PriorApproved{get;private set;}=[];public IReadOnlyList<ChecksumMatch>ChecksumMatches{get;private set;}=[];public IReadOnlyList<Option>Players{get;private set;}=[];public IReadOnlyList<RequirementOption>Requirements{get;private set;}=[];public IReadOnlyList<DropOption>Drops{get;private set;}=[];public IReadOnlyList<Option>DuplicateOptions{get;private set;}=[];
    [BindProperty]public ReviewInput Input{get;set;}=new();
    public async Task<IActionResult>OnGetAsync(Guid id,CancellationToken ct){if(!await Load(id,ct))return NotFound();Input=new(){BoardTileId=Details.TileId,RequirementId=Details.RequirementId,DropSnapshotId=Details.DropId,CreditedParticipantId=Details.PlayerId,ClaimedWeight=Details.Claimed,Note=Details.Note};return Page();}
    public Task<IActionResult>OnPostApproveAsync(Guid id,CancellationToken ct)=>Execute(id,async()=>{var amount=await service.ApproveAsync(id,User.GetAccountId()!.Value,ct);TempData["StatusMessage"]=$"Approved with {amount} contribution.";},ct);
    public Task<IActionResult>OnPostRequestChangesAsync(Guid id,CancellationToken ct)=>Execute(id,()=>service.RequestChangesAsync(id,User.GetAccountId()!.Value,Input.Note??string.Empty,ct),ct,"Changes requested. The captain can now correct and resubmit this evidence.");
    public Task<IActionResult>OnPostRejectAsync(Guid id,CancellationToken ct)=>Execute(id,()=>service.RejectAsync(id,User.GetAccountId()!.Value,Input.Note??string.Empty,null,ct),ct,"Submission rejected.");
    public Task<IActionResult>OnPostDuplicateAsync(Guid id,CancellationToken ct)=>Execute(id,()=>service.RejectAsync(id,User.GetAccountId()!.Value,Input.Note??"Duplicate submission",Input.DuplicateOfSubmissionId,ct),ct,"Submission marked as a duplicate.");
    public Task<IActionResult>OnPostReverseAsync(Guid id,CancellationToken ct)=>Execute(id,()=>service.ReverseAsync(id,User.GetAccountId()!.Value,Input.Note??string.Empty,ct),ct,"Approval reversed and later contributions recalculated.");
    public Task<IActionResult>OnPostHideVisibilityAsync(Guid id,CancellationToken ct)=>Execute(id,()=>service.SetVisibilityAsync(id,User.GetAccountId()!.Value,true,ct),ct,"Public screenshot and player hidden.");
    public Task<IActionResult>OnPostRestoreVisibilityAsync(Guid id,CancellationToken ct)=>Execute(id,()=>service.SetVisibilityAsync(id,User.GetAccountId()!.Value,false,ct),ct,"Public screenshot and player restored.");
    public Task<IActionResult>OnPostEditAsync(Guid id,CancellationToken ct)=>Execute(id,()=>service.EditMetadataAsync(new(id,User.GetAccountId()!.Value,Input.BoardTileId,Input.RequirementId,Input.DropSnapshotId,Input.CreditedParticipantId,Input.ClaimedWeight,Input.Note),ct),ct);
    private async Task<IActionResult>Execute(Guid id,Func<Task> action,CancellationToken ct,string?success=null){try{await action();if(success is not null)TempData["StatusMessage"]=success;}catch(Exception ex)when(ex is InvalidOperationException or ArgumentException){TempData["StatusMessage"]=ex.Message;}return RedirectToPage(new{id});}
    private async Task<bool>Load(Guid id,CancellationToken ct)
    {
        var s=await db.Submissions.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id,ct);if(s is null)return false;var team=await db.Teams.AsNoTracking().SingleAsync(x=>x.Id==s.TeamId,ct);var tile=await db.BoardTiles.AsNoTracking().SingleAsync(x=>x.Id==s.BoardTileId,ct);var req=await db.BoardRequirementSnapshots.AsNoTracking().SingleAsync(x=>x.Id==s.RequirementId,ct);var player=await db.EventParticipants.AsNoTracking().SingleAsync(x=>x.Id==s.CreditedParticipantId,ct);var drop=s.DropSnapshotId is null?null:await db.BoardRequirementDropSnapshots.AsNoTracking().SingleAsync(x=>x.Id==s.DropSnapshotId,ct);Details=new(s.Id,s.EventId,s.TeamId,s.BoardTileId,s.RequirementId,s.DropSnapshotId,s.CreditedParticipantId,team.Name,tile.NameSnapshot,req.Description,drop?.BossName,drop?.ItemName,player.PrimaryAccountName,s.Status,s.ClaimedWeight,s.ApprovedContribution,s.SubmittedAt,s.CaptainNote,s.CurrentReviewerNote,s.ExpectedEvidenceCode,s.PublicEvidenceHidden,s.PublicPrivacyRequested);
        Assets=await db.EvidenceAssets.AsNoTracking().Where(x=>x.SubmissionId==id).OrderByDescending(x=>x.UploadedAt).Select(x=>new AssetView(x.Id,x.OriginalFilename,x.MediaType,x.ByteSize,x.PixelWidth,x.PixelHeight,x.Checksum,x.UploadedAt,x.Role,x.Active)).ToListAsync(ct);
        var activeChecksum=Assets.FirstOrDefault(x=>x.Active)?.Checksum;if(activeChecksum is not null)ChecksumMatches=await(from asset in db.EvidenceAssets.AsNoTracking()join other in db.Submissions on asset.SubmissionId equals other.Id join otherTile in db.BoardTiles on other.BoardTileId equals otherTile.Id where asset.Checksum==activeChecksum&&asset.Active&&other.EventId==s.EventId&&other.Id!=s.Id orderby other.SubmittedAt descending select new ChecksumMatch(other.Id,otherTile.NameSnapshot,other.SubmittedAt,other.Status)).ToListAsync(ct);
        History=await(from a in db.ReviewActions.AsNoTracking()join account in db.Accounts on a.PerformedByAccountId equals account.Id where a.SubmissionId==id orderby a.PerformedAt descending select new ActionView(a.Action,account.Username,a.PerformedAt,a.Note)).ToListAsync(ct);PriorApproved=await(from other in db.Submissions.AsNoTracking()join p in db.EventParticipants on other.CreditedParticipantId equals p.Id where other.TeamId==s.TeamId&&other.RequirementId==s.RequirementId&&other.Status==SubmissionStatus.Approved&&other.Id!=s.Id orderby other.SubmittedAt descending select new ContextView(other.Id,p.PrimaryAccountName,other.ApprovedContribution,other.SubmittedAt)).ToListAsync(ct);
        Players=await(from m in db.TeamMemberships.AsNoTracking()join p in db.EventParticipants on m.EventParticipantId equals p.Id where m.TeamId==s.TeamId&&m.LeftAt==null orderby p.PrimaryAccountName select new Option(p.Id,p.PrimaryAccountName)).ToListAsync(ct);var board=await db.Boards.AsNoTracking().SingleAsync(x=>x.EventId==s.EventId,ct);var tiles=await db.BoardTiles.AsNoTracking().Where(x=>x.BoardId==board.Id).ToListAsync(ct);var tileMap=tiles.ToDictionary(x=>x.Id);var tileIds=tiles.Select(x=>x.Id).ToList();var requirements=await db.BoardRequirementSnapshots.AsNoTracking().Where(x=>tileIds.Contains(x.BoardTileId)).OrderBy(x=>x.Position).ToListAsync(ct);Requirements=requirements.Select(x=>new RequirementOption(x.Id,x.BoardTileId,tileMap[x.BoardTileId].NameSnapshot,x.Description,x.ManualObjective,x.AllowHigherWeightings)).ToList();var reqIds=requirements.Select(x=>x.Id).ToList();Drops=await db.BoardRequirementDropSnapshots.AsNoTracking().Where(x=>reqIds.Contains(x.RequirementId)).OrderBy(x=>x.BossName).ThenBy(x=>x.ItemName).Select(x=>new DropOption(x.Id,x.RequirementId,x.BossName,x.ItemName,x.DisplayRate)).ToListAsync(ct);var duplicateRows=await(from x in db.Submissions.AsNoTracking()join t in db.BoardTiles on x.BoardTileId equals t.Id where x.EventId==s.EventId&&x.Id!=s.Id orderby x.SubmittedAt descending select new{x.Id,x.SubmittedAt,t.NameSnapshot}).Take(100).ToListAsync(ct);DuplicateOptions=duplicateRows.Select(x=>new Option(x.Id,$"{x.SubmittedAt.ToLocalTime():g} · {x.NameSnapshot}")).ToList();return true;
    }
    public sealed class ReviewInput{[StringLength(4000)]public string?Note{get;set;}public Guid?DuplicateOfSubmissionId{get;set;}public Guid BoardTileId{get;set;}public Guid RequirementId{get;set;}public Guid?DropSnapshotId{get;set;}public Guid CreditedParticipantId{get;set;}[Range(1,10000)]public int ClaimedWeight{get;set;}=1;}
    public sealed record DetailsView(Guid Id,Guid EventId,Guid TeamId,Guid TileId,Guid RequirementId,Guid?DropId,Guid PlayerId,string Team,string Tile,string Requirement,string?Boss,string?Drop,string Player,SubmissionStatus Status,int Claimed,int Approved,DateTimeOffset SubmittedAt,string?CaptainNote,string?Note,string?ExpectedCode,bool PublicHidden,bool PublicPrivacyRequested);public sealed record AssetView(Guid Id,string Filename,string MediaType,long Bytes,int Width,int Height,string Checksum,DateTimeOffset UploadedAt,EvidenceAssetRole Role,bool Active);public sealed record ActionView(ReviewActionType Action,string Actor,DateTimeOffset At,string?Note);public sealed record ContextView(Guid Id,string Player,int Amount,DateTimeOffset SubmittedAt);public sealed record ChecksumMatch(Guid Id,string Tile,DateTimeOffset SubmittedAt,SubmissionStatus Status);[System.Diagnostics.CodeAnalysis.SuppressMessage("Naming","CA1716:Identifiers should not match keywords")]public sealed record Option(Guid Id,string Label);public sealed record RequirementOption(Guid Id,Guid TileId,string Tile,string Description,bool Manual,bool Higher);public sealed record DropOption(Guid Id,Guid RequirementId,string Boss,string Item,string Rate);
}
