using System.ComponentModel.DataAnnotations;
using Bingo.Application.Evidence;
using Bingo.Domain.Events;
using Bingo.Domain.Evidence;
using Bingo.Infrastructure.Persistence;
using Bingo.Web.Security;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Bingo.Web.Pages.Admin.Review;

public sealed class DetailsModel(ApplicationDbContext db, ISubmissionService service) : PageModel
{
    public DetailsView Details { get; private set; } = null!; public IReadOnlyList<AssetView> Assets { get; private set; } = []; public IReadOnlyList<ActionView> History { get; private set; } = []; public IReadOnlyList<ContextView> PriorApproved { get; private set; } = []; public IReadOnlyList<ChecksumMatch> ChecksumMatches { get; private set; } = []; public IReadOnlyList<Option> Characters { get; private set; } = []; public IReadOnlyList<RequirementOption> Requirements { get; private set; } = []; public IReadOnlyList<DropOption> Drops { get; private set; } = [];
    [BindProperty] public ReviewInput Input { get; set; } = new();
    public async Task<IActionResult> OnGetAsync(Guid id, CancellationToken ct) { if (!await Load(id, ct)) return NotFound(); Input = new() { BoardTileId = Details.TileId, RequirementId = Details.RequirementId, DropSnapshotId = Details.DropId, CreditedOsrsCharacterId = Details.CharacterId, Reason = Details.Note, ExpectedVersion = Details.Version }; return Page(); }
    public Task<IActionResult> OnPostApproveAsync(Guid id, CancellationToken ct) => Execute(id, async () => { var amount = await service.ApproveAsync(id, User.GetAccountId()!.Value, ct, Input.ExpectedVersion); TempData["StatusMessage"] = $"Approved with {amount} contribution."; }, ct);
    public Task<IActionResult> OnPostRejectAsync(Guid id, CancellationToken ct) => Execute(id, () => service.RejectAsync(id, User.GetAccountId()!.Value, Input.Reason ?? string.Empty, ct, Input.ExpectedVersion), ct, "Submission rejected.");
    public Task<IActionResult> OnPostReverseAsync(Guid id, CancellationToken ct) => Execute(id, () => service.ReverseAsync(id, User.GetAccountId()!.Value, Input.Reason ?? string.Empty, ct, Input.ExpectedVersion), ct, "Approval reversed and later contributions recalculated.");
    public Task<IActionResult> OnPostEditAsync(Guid id, CancellationToken ct) => Execute(id, () => service.EditMetadataAsync(new(id, User.GetAccountId()!.Value, Input.BoardTileId, Input.RequirementId, Input.DropSnapshotId, Input.CreditedOsrsCharacterId, Input.Reason ?? string.Empty, Input.ExpectedVersion), ct), ct, "Metadata corrected.");
    private async Task<IActionResult> Execute(Guid id, Func<Task> action, CancellationToken ct, string? success = null) { try { await action(); if (success is not null) TempData["StatusMessage"] = success; } catch (Exception ex) when (ex is InvalidOperationException or ArgumentException) { TempData["StatusMessage"] = ex.Message; } return RedirectToPage(new { id }); }
    private async Task<bool> Load(Guid id, CancellationToken ct)
    {
        var s = await db.Submissions.AsNoTracking().SingleOrDefaultAsync(x => x.Id == id, ct); if (s is null) return false; var eventItem = await db.Events.AsNoTracking().SingleAsync(x => x.Id == s.EventId, ct); var team = await db.Teams.AsNoTracking().SingleAsync(x => x.Id == s.TeamId, ct); var tile = await db.BoardTiles.AsNoTracking().SingleAsync(x => x.Id == s.BoardTileId, ct); var req = await db.BoardRequirementSnapshots.AsNoTracking().SingleAsync(x => x.Id == s.RequirementId, ct); var drop = s.DropSnapshotId is null ? null : await db.BoardRequirementDropSnapshots.AsNoTracking().SingleAsync(x => x.Id == s.DropSnapshotId, ct); var effectiveEnd = eventItem.ActualEndedAt ?? eventItem.EventEndsAt; var minutesAfterEnd = effectiveEnd is { } eventEnd && s.SubmittedAt > eventEnd ? (int?)Math.Ceiling((s.SubmittedAt - eventEnd).TotalMinutes) : null; var eligibilityGap = await FindEligibilityGapAsync(s.EventId, s.SubmittedAt, ct); Details = new(s.Id, s.EventId, s.TeamId, s.BoardTileId, s.RequirementId, s.DropSnapshotId, s.CreditedParticipantId, s.CreditedOsrsCharacterId, team.Name, tile.NameSnapshot, req.Description, drop?.BossName, drop?.ItemName, s.CreditedCharacterName, s.Status, s.ClaimedWeight, s.ApprovedContribution, s.SubmittedAt, s.CaptainNote, s.CurrentReviewerNote, s.ExpectedEvidenceCode, s.Version, minutesAfterEnd, effectiveEnd, eligibilityGap);
        Assets = await db.EvidenceAssets.AsNoTracking().Where(x => x.SubmissionId == id).OrderByDescending(x => x.UploadedAt).Select(x => new AssetView(x.Id, x.OriginalFilename, x.MediaType, x.ByteSize, x.PixelWidth, x.PixelHeight, x.Checksum, x.UploadedAt, x.Role, x.Active)).ToListAsync(ct);
        var activeChecksum = Assets.FirstOrDefault(x => x.Active)?.Checksum; if (activeChecksum is not null) ChecksumMatches = await (from asset in db.EvidenceAssets.AsNoTracking() join other in db.Submissions on asset.SubmissionId equals other.Id join otherTile in db.BoardTiles on other.BoardTileId equals otherTile.Id where asset.Checksum == activeChecksum && asset.Active && other.EventId == s.EventId && other.Id != s.Id orderby other.SubmittedAt descending select new ChecksumMatch(other.Id, otherTile.NameSnapshot, other.SubmittedAt, other.Status)).ToListAsync(ct);
        History = await (from a in db.ReviewActions.AsNoTracking() join account in db.Accounts on a.PerformedByAccountId equals account.Id where a.SubmissionId == id orderby a.PerformedAt descending select new ActionView(a.Action, account.LoginName, a.PerformedAt, a.Note)).ToListAsync(ct); PriorApproved = await db.Submissions.AsNoTracking().Where(other => other.TeamId == s.TeamId && other.RequirementId == s.RequirementId && other.Status == SubmissionStatus.Approved && other.Id != s.Id).OrderByDescending(other => other.SubmittedAt).Select(other => new ContextView(other.Id, other.CreditedCharacterName, other.ApprovedContribution, other.SubmittedAt)).ToListAsync(ct);
        Characters = await (from assignment in db.EventParticipantCharacters.AsNoTracking() join membership in db.TeamMemberships.AsNoTracking() on assignment.EventParticipantId equals membership.EventParticipantId join character in db.OsrsCharacters.AsNoTracking() on assignment.OsrsCharacterId equals character.Id where assignment.EventId == s.EventId && membership.TeamId == s.TeamId && membership.LeftAt == null && assignment.EventRole == Bingo.Domain.Signups.EventCharacterRole.Playing && assignment.ReleasedAt == null orderby character.DisplayName select new Option(character.Id, character.DisplayName)).Distinct().ToListAsync(ct); var board = await db.Boards.AsNoTracking().SingleAsync(x => x.EventId == s.EventId, ct); var tiles = await db.BoardTiles.AsNoTracking().Where(x => x.BoardId == board.Id).ToListAsync(ct); var tileMap = tiles.ToDictionary(x => x.Id); var tileIds = tiles.Select(x => x.Id).ToList(); var requirements = await db.BoardRequirementSnapshots.AsNoTracking().Where(x => tileIds.Contains(x.BoardTileId)).OrderBy(x => x.Position).ToListAsync(ct); Requirements = requirements.Select(x => new RequirementOption(x.Id, x.BoardTileId, tileMap[x.BoardTileId].NameSnapshot, x.Description, x.ManualObjective, x.AllowHigherWeightings)).ToList(); var reqIds = requirements.Select(x => x.Id).ToList(); Drops = await db.BoardRequirementDropSnapshots.AsNoTracking().Where(x => reqIds.Contains(x.RequirementId)).OrderBy(x => x.BossName).ThenBy(x => x.ItemName).Select(x => new DropOption(x.Id, x.RequirementId, x.BossName, x.ItemName, x.DisplayRate)).ToListAsync(ct); return true;
    }
    public sealed class ReviewInput { [StringLength(4000)] public string? Reason { get; set; } public Guid BoardTileId { get; set; } public Guid RequirementId { get; set; } public Guid? DropSnapshotId { get; set; } public Guid CreditedOsrsCharacterId { get; set; } public int? ExpectedVersion { get; set; } }
    private async Task<EligibilityGapView?> FindEligibilityGapAsync(Guid eventId, DateTimeOffset submittedAt, CancellationToken ct)
    {
        var transitions = await db.EventStateTransitions.AsNoTracking().Where(x => x.EventId == eventId &&
            (x.ToState == EventState.AwaitingFinalReview || x.ToState == EventState.Live)).OrderBy(x => x.EffectiveAt).ThenBy(x => x.PerformedAt).ThenBy(x => x.Id).ToListAsync(ct);
        DateTimeOffset? gapStarted = null;
        foreach (var transition in transitions)
        {
            if (transition.ToState == EventState.AwaitingFinalReview) gapStarted = transition.EffectiveAt;
            else if (transition.ToState == EventState.Live && gapStarted is { } started)
            {
                var resumed = transition.EffectiveAt;
                if (submittedAt >= started && submittedAt < resumed) return new EligibilityGapView(started, resumed);
                gapStarted = null;
            }
        }
        return null;
    }

    public sealed record DetailsView(Guid Id, Guid EventId, Guid TeamId, Guid TileId, Guid RequirementId, Guid? DropId, Guid PlayerId, Guid CharacterId, string Team, string Tile, string Requirement, string? Boss, string? Drop, string Player, SubmissionStatus Status, int Claimed, int Approved, DateTimeOffset SubmittedAt, string? CaptainNote, string? Note, string? ExpectedCode, int Version = 1, int? MinutesAfterEventEnd = null, DateTimeOffset? EventEndsAt = null, EligibilityGapView? EligibilityGap = null); public sealed record EligibilityGapView(DateTimeOffset StartedAt, DateTimeOffset ResumedAt); public sealed record AssetView(Guid Id, string Filename, string MediaType, long Bytes, int Width, int Height, string Checksum, DateTimeOffset UploadedAt, EvidenceAssetRole Role, bool Active); public sealed record ActionView(ReviewActionType Action, string Actor, DateTimeOffset At, string? Note); public sealed record ContextView(Guid Id, string Player, int Amount, DateTimeOffset SubmittedAt); public sealed record ChecksumMatch(Guid Id, string Tile, DateTimeOffset SubmittedAt, SubmissionStatus Status); [System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1716:Identifiers should not match keywords")] public sealed record Option(Guid Id, string Label); public sealed record RequirementOption(Guid Id, Guid TileId, string Tile, string Description, bool Manual, bool Higher); public sealed record DropOption(Guid Id, Guid RequirementId, string Boss, string Item, string Rate);
}
