using System.ComponentModel.DataAnnotations;
using Bingo.Application.Evidence;
using Bingo.Domain.Boards;
using Bingo.Domain.Events;
using Bingo.Infrastructure.Persistence;
using Bingo.Web.Security;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Bingo.Web.Pages.Admin.Review;

[RequestSizeLimit(11 * 1024 * 1024)]
public sealed class SubmitModel(ApplicationDbContext db, ISubmissionService service) : PageModel
{
    [BindProperty(SupportsGet = true)] public Guid EventId { get; set; }
    public string EventName { get; private set; } = string.Empty; public IReadOnlyList<Option> Teams { get; private set; } = []; public IReadOnlyList<PlayerOption> Players { get; private set; } = []; public IReadOnlyList<TileOption> Tiles { get; private set; } = []; public IReadOnlyList<RequirementOption> Requirements { get; private set; } = []; public IReadOnlyList<DropOption> Drops { get; private set; } = [];
    [BindProperty] public InputModel Input { get; set; } = new(); public async Task<IActionResult> OnGetAsync(CancellationToken ct) => await Load(EventId, ct) ? Page() : RedirectToPage("Index");
    public async Task<IActionResult> OnPostAsync(CancellationToken ct) { if (!await Load(EventId, ct)) return RedirectToPage("Index"); if (Input.Evidence is null) ModelState.AddModelError("Input.Evidence", "Choose evidence."); if (!ModelState.IsValid) return Page(); try { await using var stream = Input.Evidence!.OpenReadStream(); var result = await service.CreateAsync(new(User.GetAccountId()!.Value, EventId, Input.TeamId, Input.BoardTileId, Input.RequirementId, Input.DropSnapshotId, Input.CreditedParticipantId, Input.ClaimedWeight, Input.Note, Input.Evidence.FileName, stream), ct); return RedirectToPage("Details", new { id = result.SubmissionId }); } catch (InvalidOperationException ex) { ModelState.AddModelError(string.Empty, ex.Message); return Page(); } }
    private async Task<bool> Load(Guid eventId, CancellationToken ct) { var ev = await db.Events.AsNoTracking().SingleOrDefaultAsync(x => x.Id == eventId && (x.State == EventState.Live || x.State == EventState.AwaitingFinalReview), ct); if (ev is null) return false; EventId = ev.Id; EventName = ev.Name; Teams = await db.Teams.AsNoTracking().Where(x => x.EventId == ev.Id && x.Active).OrderBy(x => x.Name).Select(x => new Option(x.Id, x.Name)).ToListAsync(ct); var teamIds = Teams.Select(x => x.Id).ToList(); Players = await (from m in db.TeamMemberships.AsNoTracking() join p in db.PrimaryCharacters() on m.EventParticipantId equals p.ParticipantId where teamIds.Contains(m.TeamId) && m.LeftAt == null orderby p.Name select new PlayerOption(p.ParticipantId, m.TeamId, p.Name)).ToListAsync(ct); var board = await db.Boards.AsNoTracking().SingleOrDefaultAsync(x => x.EventId == ev.Id && x.State == BoardState.Published, ct); if (board is null) return false; Tiles = await db.BoardTiles.AsNoTracking().Where(x => x.BoardId == board.Id).OrderBy(x => x.RowIndex).ThenBy(x => x.ColumnIndex).Select(x => new TileOption(x.Id, x.NameSnapshot)).ToListAsync(ct); var tileIds = Tiles.Select(x => x.Id).ToList(); Requirements = await db.BoardRequirementSnapshots.AsNoTracking().Where(x => tileIds.Contains(x.BoardTileId)).OrderBy(x => x.Position).Select(x => new RequirementOption(x.Id, x.BoardTileId, x.Description, x.ManualObjective, x.AllowHigherWeightings)).ToListAsync(ct); var ids = Requirements.Select(x => x.Id).ToList(); Drops = await db.BoardRequirementDropSnapshots.AsNoTracking().Where(x => ids.Contains(x.RequirementId)).OrderBy(x => x.BossName).ThenBy(x => x.ItemName).Select(x => new DropOption(x.Id, x.RequirementId, x.BossName, x.ItemName, x.DisplayRate)).ToListAsync(ct); return true; }
    public sealed class InputModel { [Required] public Guid TeamId { get; set; } [Required] public Guid BoardTileId { get; set; } [Required] public Guid RequirementId { get; set; } public Guid? DropSnapshotId { get; set; } [Required] public Guid CreditedParticipantId { get; set; } [Range(1, 10000)] public int ClaimedWeight { get; set; } = 1; [StringLength(4000)] public string? Note { get; set; } public IFormFile? Evidence { get; set; } }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1716:Identifiers should not match keywords")] public sealed record Option(Guid Id, string Name); public sealed record PlayerOption(Guid Id, Guid TeamId, string Name); public sealed record TileOption(Guid Id, string Name); public sealed record RequirementOption(Guid Id, Guid TileId, string Description, bool Manual, bool Higher); public sealed record DropOption(Guid Id, Guid RequirementId, string Boss, string Item, string Rate);
}
